### PR TITLE
Verified on CentOS 7.9.2009

### PR DESCRIPTION
**Pull request by jkan-cn**
Signed-off-by: jkan-cn <jalen.j.kan@seagate.com>

change test by

Verified on CentOS 7.9.2009

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by mehjoshi** [comment]
retest this please

**Comment by jkan-cn** [comment]
Will retest this and close it first.

**Comment by mehjoshi** [comment]
@jkan-cn , "retest this please" is just a trigger phrase for our jenkins CI.

**Pull request closed without merging**
