### PR TITLE
Cortx-30054: Experimental: Initial code changes for sns direct rebalance 

### PR DESCRIPTION
**Pull request by mehjoshi**
# Problem Statement
- Study the existing SNS repair code and experiment for implementing direct rebalance functionality.

# Design
- NA: This experimental code.

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- This is WIP and not for official review

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by gauravchaudhari02** [comment]
rerun vm-deployment

**Comment by Abhirup-A-G** [comment]
retest this please - rerunning automated vm-deployment

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete

**Pull request closed without merging**
