### PR TITLE
EOS-7849 Add assert for NULL pointer check to catch freeing NULL pointer cases…

### PR DESCRIPTION
**Pull request by jamohite**
… in m0_be_free_aligned()

### CODE REVIEW

**Review by huanghua78 — APPROVED** [review]
Looks fine.

**Comment by huanghua78** [comment]
@jamohite , what is the status of this PR?

**Comment by jamohite** [comment]
> @jamohite , what is the status of this PR?

rebased this branch with latest main branch

**Review by huanghua78 — APPROVED** [review]

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138/>Motr#138</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>1</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0223m0d-signal-test target=_blank>0223m0d-signal-test</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0137protocol target=_blank>0137protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0431motr-sys-kvs-kernel-test target=_blank>0431motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0507multi-client-tests target=_blank>0507multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0539mount-fail target=_blank>0539mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0512sns-cc-io-tests target=_blank>0512sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>57</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0146m0crate target=_blank>0146m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0101kernel-tests target=_blank>0101kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0100userspace-tests target=_blank>0100userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0103initscript-tests target=_blank>0103initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0130hagen-test target=_blank>0130hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0129confgen-test target=_blank>0129confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0135m0singlenode target=_blank>0135m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0104net-tests target=_blank>0104net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0105rpcping-tests target=_blank>0105rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0128motr-sys-kvs-test target=_blank>0128motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0106console-tests target=_blank>0106console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0152singlenode-sanity target=_blank>0152singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0220pool-version-test target=_blank>0220pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0221spiel-test target=_blank>0221spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0247motr-tests-user-kernel target=_blank>0247motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0209poolmach-tests target=_blank>0209poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0241motr-conf-update target=_blank>0241motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0208degraded-mode-tests target=_blank>0208degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0224m0d-fsync-test target=_blank>0224m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0202system-tests target=_blank>0202system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0222rpc-cancel-test target=_blank>0222rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0253clusterusage-alert target=_blank>0253clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0251kem target=_blank>0251kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0354sns-repair-motr-1f target=_blank>0354sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0359sns-repair-motr-abort target=_blank>0359sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0317sss-st-test target=_blank>0317sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0358sns-repair-motr-ios-fail target=_blank>0358sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0360sns-repair-motr-abort-quiesce target=_blank>0360sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0355sns-repair-motr-1n-1f target=_blank>0355sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0356sns-repair-motr-mf target=_blank>0356sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0361spiel-multi-confd target=_blank>0361spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0316conf-st-test target=_blank>0316conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0357sns-repair-motr-1k-1f target=_blank>0357sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0336spare-reservation target=_blank>0336spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0451motr-rmw target=_blank>0451motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0450motr-rm-lock-cc-io target=_blank>0450motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0425spiel-sns-repair-test target=_blank>0425spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0433motr-st target=_blank>0433motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0419sns-abort-test target=_blank>0419sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0432m0t1fs-rconfc-fail-test target=_blank>0432m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0434sns-repair-1n-1f target=_blank>0434sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0426spiel-sns-repair-quiesce-test target=_blank>0426spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0449motr-rpc-cancel target=_blank>0449motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0427sns-repair-io-fail-test target=_blank>0427sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0448motr-raid0-io target=_blank>0448motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0540motr-dgmode target=_blank>0540motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0542motr-utils target=_blank>0542motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0513sns-repair-quiesce target=_blank>0513sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0545motr-sns-repair-N-1 target=_blank>0545motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0511sns-multi-tests target=_blank>0511sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0544motr-sns-repair target=_blank>0544motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0514m0t1fs-fsync-test target=_blank>0514m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0543motr-sync-replication target=_blank>0543motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0538sns-abort-quiesce-test target=_blank>0538sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0515m0t1fs-fwait-test target=_blank>0515m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0518m0mount-test target=_blank>0518m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node/0510sns-single-tests target=_blank>0510sns-single-tests</a></p></details></td></tr><tr><td>Total</td><td>63</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/138//testReport/junit/motr-single-node>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147/>Motr#147</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>2</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0128motr-sys-kvs-test target=_blank>0128motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0223m0d-signal-test target=_blank>0223m0d-signal-test</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0137protocol target=_blank>0137protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0431motr-sys-kvs-kernel-test target=_blank>0431motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0507multi-client-tests target=_blank>0507multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0539mount-fail target=_blank>0539mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0512sns-cc-io-tests target=_blank>0512sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>56</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0146m0crate target=_blank>0146m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0101kernel-tests target=_blank>0101kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0100userspace-tests target=_blank>0100userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0103initscript-tests target=_blank>0103initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0130hagen-test target=_blank>0130hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0129confgen-test target=_blank>0129confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0135m0singlenode target=_blank>0135m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0104net-tests target=_blank>0104net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0105rpcping-tests target=_blank>0105rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0106console-tests target=_blank>0106console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0152singlenode-sanity target=_blank>0152singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0220pool-version-test target=_blank>0220pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0221spiel-test target=_blank>0221spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0247motr-tests-user-kernel target=_blank>0247motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0209poolmach-tests target=_blank>0209poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0241motr-conf-update target=_blank>0241motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0208degraded-mode-tests target=_blank>0208degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0224m0d-fsync-test target=_blank>0224m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0202system-tests target=_blank>0202system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0222rpc-cancel-test target=_blank>0222rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0253clusterusage-alert target=_blank>0253clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0251kem target=_blank>0251kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0354sns-repair-motr-1f target=_blank>0354sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0359sns-repair-motr-abort target=_blank>0359sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0317sss-st-test target=_blank>0317sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0358sns-repair-motr-ios-fail target=_blank>0358sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0360sns-repair-motr-abort-quiesce target=_blank>0360sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0355sns-repair-motr-1n-1f target=_blank>0355sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0356sns-repair-motr-mf target=_blank>0356sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0361spiel-multi-confd target=_blank>0361spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0316conf-st-test target=_blank>0316conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0357sns-repair-motr-1k-1f target=_blank>0357sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0336spare-reservation target=_blank>0336spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0451motr-rmw target=_blank>0451motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0450motr-rm-lock-cc-io target=_blank>0450motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0425spiel-sns-repair-test target=_blank>0425spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0433motr-st target=_blank>0433motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0419sns-abort-test target=_blank>0419sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0432m0t1fs-rconfc-fail-test target=_blank>0432m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0434sns-repair-1n-1f target=_blank>0434sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0426spiel-sns-repair-quiesce-test target=_blank>0426spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0449motr-rpc-cancel target=_blank>0449motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0427sns-repair-io-fail-test target=_blank>0427sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0448motr-raid0-io target=_blank>0448motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0540motr-dgmode target=_blank>0540motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0542motr-utils target=_blank>0542motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0513sns-repair-quiesce target=_blank>0513sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0545motr-sns-repair-N-1 target=_blank>0545motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0511sns-multi-tests target=_blank>0511sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0544motr-sns-repair target=_blank>0544motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0514m0t1fs-fsync-test target=_blank>0514m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0543motr-sync-replication target=_blank>0543motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0538sns-abort-quiesce-test target=_blank>0538sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0515m0t1fs-fwait-test target=_blank>0515m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0518m0mount-test target=_blank>0518m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node/0510sns-single-tests target=_blank>0510sns-single-tests</a></p></details></td></tr><tr><td>Total</td><td>63</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/147//testReport/junit/motr-single-node>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

**Pull request merged**
