### PR TITLE
Swatid patch addb

### PR DESCRIPTION
**Pull request by swatid-seagate**
# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

-----
[View rendered Motr-Terminology-Guide.md](https://github.com/swatid-seagate/cortx-motr/blob/swatid-patch-ADDB/Motr-Terminology-Guide.md)
[View rendered doc/ADDB.md](https://github.com/swatid-seagate/cortx-motr/blob/swatid-patch-ADDB/doc/ADDB.md)
[View rendered doc/motr-in-prose.md](https://github.com/swatid-seagate/cortx-motr/blob/swatid-patch-ADDB/doc/motr-in-prose.md)

### CODE REVIEW

**Comment by mehjoshi** [comment]
@swatid-seagate , we already have an ADDB.rst file and its contents are the same as of the ADDB.md file that is being added in this PR. Do we need both?

**Comment by swatid-seagate** [comment]
Once this .md file is uploaded, we need to either archive or delete the .rst file.

**Comment by mehjoshi** [comment]
> Once this .md file is uploaded, we need to either archive or delete the .rst file.

You can do it together in the same commit or PR.

**Comment by swatid-seagate** [comment]
> > Once this .md file is uploaded, we need to either archive or delete the .rst file.
> 
> You can do it together in the same commit or PR.

**Comment by swatid-seagate** [comment]
I don't know who will take the decision whether to archive or delete the files. If possible, please let me know and I will make relative changes.

**Comment by mehjoshi** [comment]
@swatid-seagate , Please resolve the conflicts.

**Review by mehjoshi — APPROVED** [review]

**Pull request merged**
