### PR TITLE
Update Quick-Start-Guide.rst

### PR DESCRIPTION
**Pull request by mengwanguc**
Add prerequisites for running "make doc". 
Latex and ghostscript are required.
Otherwise will get errors. See #775 

Signed-off-by: Meng Wang <mengwanguc@gmail.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by mengwanguc** [comment]
Hi @mehjoshi , can you please review this PR? Thank you very much!

**Review by mehjoshi — APPROVED** [review]
Looks good to me.

**Comment by mengwanguc** [comment]
Hello, can someone else review this PR so that we get two approvals? Thank you very much!

(btw, I'm a Seagate employee so I don't need to sign the CLA)

**Comment by mehjoshi** [comment]
> (btw, I'm a Seagate employee so I don't need to sign the CLA)
The CLA needs to be signed by all code submitters, even Seagate employees. It can be waived-off in certain cases where the code submitter is external to Seagate and where the changes submitted are for minor additions or documentation. @mukul-seagate11 can confirm this.

**Comment by mehjoshi** [comment]
Hi @mengwanguc, I saw the update from @johnbent in the other PR(#838 ) and accordingly I reason that the CLA may not be required in the current PR either.
I will merge this once it gets a second approver. Thanks!

**Comment by huanghua78** [comment]
This PR needs to be verified for the proposed changes.

**Review by mehjoshi — CHANGES_REQUESTED** [review]
I tested the changes on a freshly deployed centos7.8. Apart from the packages identified in the patch, I just needed to add the doxygen package. Nothing else.
Could you please update your patch to include "sudo yum install doxygen" ?
Then it will be complete and I will merge it.

**Comment by mengwanguc** [comment]
> I tested the changes on a freshly deployed centos7.8. Apart from the packages identified in the patch, I just needed to add the doxygen package. Nothing else.
> @mengwanguc Could you please update your patch to include "sudo yum install doxygen" ?
> Then it will be complete and I will merge it.

Thanks Mehul! I've updated it.

**Review by mehjoshi — APPROVED** [review]

**Comment by mehjoshi** [comment]
@madhavemuri Could you please review?

**Review by huanghua78 — APPROVED** [review]

**Pull request merged**
