### PR TITLE
FDMI-Design-notes.md file upload

### PR DESCRIPTION
**Pull request by swatid-seagate**
Signed-off-by: Swati Dhotarkar <swati.dhotarkar@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

-----
[View rendered doc/Seagate-FDMI-Design-Notes.md](https://github.com/swatid-seagate/cortx-motr/blob/FDMI-DesignNotes/doc/Seagate-FDMI-Design-Notes.md)

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by swatid-seagate** [comment]
Though the changes are suggested, they are not crucial and this PR can be merged.

**Comment by mehjoshi** [comment]
> Though the changes are suggested, they are not crucial and this PR can be merged.

@johnbent , @novium258, Can one of your approve this for merge? Thanks.

**Review by johnbent — CHANGES_REQUESTED** [review]
@swatid-seagate , is this a newly added file? If so, you also need to add a link to it from an existing file.

**Comment by johnbent** [comment]
> 

@mehjoshi , I asked @swatid-seagate  to make a change. Will approve once that change is made. Thanks!

**Comment by r-wambui** [comment]
@swatid-seagate Could you please update on the status of this, did you make the changes requested?

**Comment by swatid-seagate** [comment]
> @swatid-seagate , is this a newly added file? If so, you also need to add a link to it from an existing file.

**Comment by swatid-seagate** [comment]
@johnbent This is a new file upload. I am bit confused as to which existing file are you referring to link to? Up to my understanding, once uploaded, this file will be linked with readinglist.md . Hope it is the right understanding.

**Comment by johnbent** [comment]
Thanks @swatid-seagate . So this same pull request should include a change to readinglist.md so that when the PR is merged, the new page exists AND it is linked. Can you please do the needful?

**Comment by swatid-seagate** [comment]
Duplicate PR. Closing it.

**Pull request closed without merging**
