### PR TITLE
Update example1.c

### PR DESCRIPTION
**Pull request by rahul-seagate**

### CODE REVIEW

**Review by huanghua78 — APPROVED** [review]

**Review by nihar1313 — APPROVED** [review]

**Comment by huanghua78** [comment]
@rahul-seagate , please follow the instructions in "DCO" to add Signed-off-by signature.

**Comment by huanghua78** [comment]
@rahul-seagate , please follow the instructions in "DCO" to add Signed-off-by signature.

**Comment by huanghua78** [comment]
@rahul-seagate , please follow the instructions in "DCO" to add Signed-off-by signature.

**Comment by huanghua78** [comment]
The author is not responded to update request.

**Pull request closed without merging**
