### PR TITLE
add link to motr rust api

### PR DESCRIPTION
**Pull request by mengwanguc**
Add a link to motr rust API.

Signed-off-by: Meng Wang <mengwanguc@gmail.com>

-----
[View rendered doc/motr-developer-guide.md](https://github.com/mengwanguc/cortx-motr/blob/patch-16/doc/motr-developer-guide.md)

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by huanghua78** [comment]
Let's add @johnbent to review this PR.
Is it good to add such a link to personal github repo?

**Comment by mengwanguc** [comment]
> Let's add @johnbent to review this PR. Is it good to add such a link to personal github repo?

I can move the codes to the motr repo. Let me try to create another PR.

**Comment by mengwanguc** [comment]
> Let's add @johnbent to review this PR. Is it good to add such a link to personal github repo?

Hi Huang, I just merged my code into motr repo and made another PR: #2012 

I tried my best to follow the developer guide coding style. But it's my first time to commit my own codes, so please bear with me if there are mistakes in my codes.

Thanks!
Meng

**Comment by huanghua78** [comment]
> > Let's add @johnbent to review this PR. Is it good to add such a link to personal github repo?
> 
> Hi Huang, I just merged my code into motr repo and made another PR: #2012
> 
> I tried my best to follow the developer guide coding style. But it's my first time to commit my own codes, so please bear with me if there are mistakes in my codes.
> 
> Thanks! Meng

Thank you very much.
Let's move to #2012.

**Pull request closed without merging**
