### PR TITLE
Perfline module added

### PR DESCRIPTION
**Pull request by ArtObr**
Adding perfline module that allows to automate workloads in a convenient way
It consist of three modules:

- perfline - main functionality, report generator, statistic gather scripts
- webui - web server for presenting workload result and controlling over new workloads
- ansible_setup - ansible script for fast perfline setup

### CODE REVIEW

**Comment by huanghua78** [comment]
@ArtObr Can you please ask someone in the team to review this?

**Comment by huanghua78** [comment]
Hello @ArtObr ,

Please check if this PR is still valid and needed.
If not, please close it.
If yes, please update the status.

**Comment by ArtObr** [comment]
Hello @huanghua78, sorry, but I'm not longer responsible por this functionality. 
@alexsukhachev @

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by alexsukhachev** [comment]
This PR is not needed anymore. All code was moved into seagate-tools repo. This PR needs to be closed.

**Comment by huanghua78** [comment]
> This PR is not needed anymore. All code was moved into seagate-tools repo. This PR needs to be closed.

Thank you.

**Pull request closed without merging**
