### PR TITLE
This PR  is simply for  merging  sage-arm-port2  to sage_arm_port  branch. It is only for upkeep of the sage_arm_port branch 

### PR DESCRIPTION
**Pull request by Nalini-Seagate**
This PR is simply for merging sage-arm-port2 to sage_arm_port branch. It is only for upkeep of the sage_arm_port branch

-----
[View rendered CONTRIBUTING.md](https://github.com/Nalini-Seagate/cortx-motr/blob/sage_arm_port/CONTRIBUTING.md)
[View rendered SUPPORT.md](https://github.com/Nalini-Seagate/cortx-motr/blob/sage_arm_port/SUPPORT.md)

### CODE REVIEW

**Comment by andriytk** [comment]
There is no need for this PR. If you want to rename `sage_arm_port2` branch to `sage_arm_port` - just delete the old branch and create the new one.

**Comment by Nalini-Seagate** [comment]
This PR is reopened as per the suggestion by Ganesan

**Comment by andriytk** [comment]
The only proper way to merge it is to rebase and merge. (Otherwise, all the unrelated commits which are already in the main branch have to be squashed in a big commit - which is, of course, wrong.). But in this case, there are a lot of conflicts to be resolved. And it's not worth to waste the time on it.

**Comment by Nalini-Seagate** [comment]
> The only proper way to merge it is to rebase and merge. (Otherwise, all the unrelated commits which are already in the main branch have to be squashed in a big commit - which is, of course, wrong.). But in this case, there are a lot of conflicts to be resolved. And it's not worth to waste the time on it.

**Comment by Nalini-Seagate** [comment]
Andriy , It is Ok that main commit history  will be purged in the course of  merging to sage-arm-port branch. Since this branch is exclusively for maintaining the ARM base branches( sage-base-1.0 , sage-base-2.0), it is immaterial for keeping the main branch history rather than keeping the  arm rebased branch. But whenever it will rebased to main branch in due time, the whole sage-arm-port will squashed and merged to main branch.

**Comment by Nalini-Seagate** [comment]
Reopened the PR

**Comment by andriytk** [comment]
Ok, I just merged it without squashing. Please check.

**Pull request merged**
