### PR TITLE
Adding fdmi_app_hello file missing from previous PR: https://github.c…

### PR DESCRIPTION
**Pull request by lia54**
…om/Seagate/cortx-motr/pull/1208

# Problem Statement
- There is a missing fdmi_app_hello file in the fdmi/plugins directory from updates done to FDMI documentation in the PR https://github.com/Seagate/cortx-motr/pull/1208 as pointed out in this issue: https://github.com/Seagate/cortx-motr/issues/1372.

# Design
-  N/A

# Coding
   Checklist for Author
-  [x ] Coding conventions are followed and code is consistent

# Testing 
N/A

# Impact Analysis
N/A

# Review Checklist 
N/A

# Documentation
N/A

Signed-off-by: Liana Valdes <lianavaldesrdguez@gmail.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by huanghua78 — APPROVED** [review]

**Comment by madhavemuri** [comment]
@huanghua78 : Can ST be added using this or other FDMI utils ?

**Comment by huanghua78** [comment]
madhavemuri commented 23 hours ago
@huanghua78 : Can ST be added using this or other FDMI utils ?

I think this serves as a demo program, and readers should follow the `fdmi/plugins/motr-fdmi-app.md` and do the demo step by step. So, no need to include it in a ST.
Also, a similar ST is already included in the system to test FDMI.

**Review by mehjoshi — APPROVED** [review]

**Comment by mehjoshi** [comment]
> Thanks for your contribution! The CLA bot has flagged your contribution as not having a Contributor License Agreement in place. Note that this is not needed in the overwhelming majority of instances and this warning will usually be ignored. The code reviewers will make a determination and may ask you to sign a CLA or may choose to ignore this warning. More information about this can be found [here](https://github.com/Seagate/cortx/blob/master/doc/dco_cla.md).

@lia54, The DCO and CLA checks are failing for this PR. Kindly resolve them.

**Comment by chandradharraval** [comment]
@lia54 - Can you check about DCO and CLA checks which are failing for this PR?

**Pull request merged**
