### PR TITLE
CORTX-33702 - [Codacy code cleanup] occurrence: 459 pattern: warn when the spacing between a list item's bullet and its content violates

### PR DESCRIPTION
**Pull request by RohanDhodare**
Updating Data-Organization.md, CORTX-MOTR_ARCHITECTURE..md, DTM.md, FDMI-High-Level-Decomposition.md, FOPFOM-Programming-Guide.md, Running_Motr_Across_a_Cluster.md, Seagate-FDMI-HLD.md, coding-style.md for formatting issues.

Signed-off-by: Rohan Dhodare <rohan.v.dhodare@seagate.com>

# Problem : 

[Codacy code cleanup] : warn when the spacing between a list item's bullet and its content violates

# Design:

- Added 2 spaces after list item 

# Coding
  Checklist for Author
- [ ] Coding conventions are followed and code is consistent

# Testing
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ]  Interface change (if any) are documented
- [ ]  Side effects on other features (deployment/upgrade)
 - [ ] Dependencies on other component(s)

## Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

## Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

-----
[View rendered doc/Data-Organization.md](https://github.com/RohanDhodare/cortx-motr/blob/test/doc/Data-Organization.md)

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by swatid-seagate — APPROVED** [review]

**Comment by RohanDhodare** [comment]
Updated new file CORTX-MOTR-ARCHITECTURE.md with its formatting issues

**Review by swatid-seagate — APPROVED** [review]
Approved the changes.

**Comment by RohanDhodare** [comment]
This PR has a lot of wrong commits so closing it.

**Pull request closed without merging**
