### PR TITLE
EOS-14409 be/tool/beck: provide option to resume scan

### PR DESCRIPTION
**Pull request by mukundkanekar**
Problem:
Beck tool crashes when run into out of memory. Motr recovery script relaunches beck which starts scan from offset 0 again. This can cause recovery run to take longer time.

Solution:
Save offsets of metadata record currently being processed by builder for each partition and worker. This offsets indicates previous metadata records are processed and are in persistent state. Beck tool relaunch can start from saved offset.

beck tool is updated to,
a. take command line argument's for file name to save scan offset and enable scan resume from saved offset.
b. save current metadata record offset for all partitions/workers periodically.
motr recovery script change to,
a. provide file name to save scan offset.
b. enable scan resume on beck tool relaunch.
c. relaunch beck tool on Out Of Memory exit code in addition to previous SEG fault.

### CODE REVIEW

**Review by kanchan-chaudhari — APPROVED** [review]
Approved changes for motr_data_recovery.sh file.

**Comment by huanghua78** [comment]
Why are there so many commits in this PR?
Can you create a new branch based on main, and apply the changes in this patch?

**Comment by mukundkanekar** [comment]
> Why are there so many commits in this PR?
These changes are based on perf changes done via EOS-14234. There were multiple PRs with multiple commits in each for EOS-14234. Till the point these PRs were not merged to main there was manual merges to current dev branch. 
> Can you create a new branch based on main, and apply the changes in this patch?
Sure. There looks to be white spaces issue in 'be/tool/beck.c ' file in main branch leading the diff is shown as whole file. Once that is resolved will create new branch and apply this patch.

**Review by ydb242 — APPROVED** [review]

**Comment by mukundkanekar** [comment]
@huanghua78  as per your suggestion created new PR #241 with just these changes.

closing this PR.

**Pull request closed without merging**
