### PR TITLE
Updated last tested

### PR DESCRIPTION
**Pull request by Saumya-Sunder**
Updated last tested

Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

### CODE REVIEW

**Comment by huanghua78** [comment]
What is the purpose of adding this paragraph into the last section of the document? @Saumya-Sunder

**Comment by Saumya-Sunder** [comment]
We think that it would be a good idea for the contributors to know when was a document last tested to know whether the information is up to date. @johnbent did I get that right?

**Review by huanghua78 — APPROVED** [review]
Looks fine.

**Review by mukul-seagate11 — APPROVED** [review]
Ok

**Pull request merged**
