### PR TITLE
doc: add state machine documentation

### PR DESCRIPTION
**Pull request by andriytk**
These are commits to doc/sm/ from the [documentation](https://github.com/Seagate/cortx-motr/tree/documentation) branch.

### CODE REVIEW

**Comment by huanghua78** [comment]
Hello @andriytk, are these documents moved from "documentation" branch?

**Comment by andriytk** [comment]
Yes, @nikitadanilov asked to land them separately.

**Review by huanghua78 — APPROVED** [review]

**Comment by huanghua78** [comment]
Hello @nikitadanilov , please review this PR.

**Comment by andriytk** [comment]
@huanghua78, it was already reviewed at https://github.com/Seagate/cortx-motr/pull/665.

**Pull request merged**
