### PR TITLE
Update Quick-Start-Guide.rst

### PR DESCRIPTION
**Pull request by yanqingfu**
added test information

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by huanghua78 — APPROVED** [review]
Thank you, @yanqingfu .

**Comment by huanghua78** [comment]
@yanqingfu please follow the instructions in DCO to fix issues there.

**Comment by yanqingfu** [comment]
> @yanqingfu please follow the instructions in DCO to fix issues there.

let me try again

**Pull request closed without merging**
