### PR TITLE
m0_fom_locality::fl_runrun: update URL.

### PR DESCRIPTION
**Pull request by nikitadanilov**
Signed-off-by: Nikita Danilov <nikita.danilov@seagate.com>

### CODE REVIEW

**Review by andriytk — APPROVED** [review]

**Comment by mehjoshi** [comment]
run vm-deployment

**Comment by mehjoshi** [comment]
"run vm-deployment"

**Comment by mehjoshi** [comment]
retest this please

**Comment by mehjoshi** [comment]
VM Deployment for 7.9 is successful. So, we can consider VM deployment passed. Hence merging this.

**Pull request merged**
