### PR TITLE
go/mio: update after m0_obj_op() API change

### PR DESCRIPTION
**Pull request by andriytk**
Motr API was changed at commit 3a429ad57: attr[] parameter to
m0_obj_op() has to be NULL now if there are no checksums in it.

### CODE REVIEW

**Comment by madhavemuri** [comment]
@yeshpal-jain-seagate : Can you check if a flag can be added instead of checking for attribute to be NULL, so that old API compatibility can be maintained ?

**Review by nikitadanilov — APPROVED** [review]

**Comment by mehjoshi** [comment]
@yeshpal-jain-seagate , @andriytk , Is an alternative approach, as suggested by @madhavemuri, using a flag instead of NULL values being tried?

**Comment by andriytk** [comment]
@mehjoshi I hope so. Ask @truptiatseagate or @madhavemuri .

**Comment by andriytk** [comment]
This patch is not needed anymore, the compatibility issue has been fixed by #1345.

**Pull request closed without merging**
