### PR TITLE
go/mio: fix go get on the module

### PR DESCRIPTION
**Pull request by kiwionly2**
Running "go get github.com/Seagate/cortx-motr/bindings/go" receive warning:

module declares its path as: cortx-motr/bindings/go
but was required as: github.com/Seagate/cortx-motr/bindings/go

Solution is change the module name to "github.com/Seagate/cortx-motr/bindings/go" so it could work with go modules.

Signed-off-by: kiwionly2 <gheewooi.ong@seagate.com>

# Problem Statement
When running `go get github.com/Seagate/cortx-motr/bindings/go`, it complains about the package name:

image

The solution is to change module name `/cortx-motr/bindings/go` to `github.com/Seagate/cortx-motr/bindings/go`.

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by kiwionly2** [comment]
@andriytk

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by andriytk** [comment]
Thank you @kiwionly2 for this. Could you please update the PR title and the commit msg to align with the previous commits to go/mio, i.e. 1) using `go/mio: ` prefix; 2) short summary line; 3) adding problem description and solution in the commit msg...

**Comment by kiwionly2** [comment]
I had done the change, however, I still find no way to merge the commits to 1, this is due to after merge, many commit had been pull to the branch, any idea to resolve this ?

**Review by andriytk — APPROVED** [review]
Thank you, @kiwionly2!

**Review by madhavemuri — APPROVED** [review]

**Comment by kiwionly2** [comment]
@rkothiya  I had pull the latest code and retest, the code could compile as expected.

Note that do to the test, you need switch to this branch `gomod` because of `go.mod` module declaration.

**Comment by rkothiya** [comment]
@kiwionly2 "retest this please" is a command to fire 1/3 node deployment jobs  and there is no action on you.

**Comment by rkothiya** [comment]
retest this please

**Comment by rkothiya** [comment]
As per discussion with Madhav, no need to run ci/cd for this as it wont cover this, hence giving an exception.

**Pull request merged**
