### PR TITLE
Added the HSM links in the ReadMe file

### PR DESCRIPTION
**Pull request by TechWriter-Mayur**
Added the Sage links in HSM ReadMe file.

Signed-off-by: TechWriter-Mayur <mayur.gupta@seagate.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by andriytk** [comment]
Should not these doc go to doc/hsm folder or something?

**Comment by TechWriter-Mayur** [comment]
> Should not these doc go to doc/hsm folder or something?

@johnbent asked we to add here. If everyone agrees, I can create a hsm folder in doc repo and add these files there.

**Comment by andriytk** [comment]
I thought all Motr docs are stored at doc/ folder, isn't it so?

**Comment by andriytk** [comment]
So looks like the document are already there at doc/PDFs/ folder, right?

**Comment by TechWriter-Mayur** [comment]
> So looks like the document are already there at doc/PDFs/ folder, right?

Yes, I think the files are same. Can we add the required links to readme and remove the duplicate files from the hsm folder?

**Comment by andriytk** [comment]
We certainly should not create the duplicate files.

**Comment by johnbent** [comment]
<table><tbody><tr><td>Yes, I think the files are same. Can we add the required links to readme and remove the duplicate files from the hsm folder?</td></tr></tbody></table>

Exactly!  Thanks both!

**Review by andriytk — APPROVED** [review]

**Comment by andriytk** [comment]
Please, update the title and the description of this PR also according to the latest changes.

**Comment by nezzzu** [comment]
@huanghua78 This is urgently needed for IO-SEA project. Is it possible to speed up the merge?

**Review by huanghua78 — APPROVED** [review]
It looks fine to me.

**Comment by johnbent** [comment]
Thanks.  With the two approvals, I went ahead and merged.  Hope that's cool.
________________________________

**Pull request merged**
