### PR TITLE
CORTX-32108: Convert Motr HLD documents from .rst to .md format

### PR DESCRIPTION
**Pull request by swatid-seagate**
# Problem Statement
   - Convert Motr HLD documents from .rst to .md format
 
# Design
   This PR contains changes to convert the following Motr HLD documents from .rst to .md format:
   - HLD-Background-Scrub.md
   - HLD-Capability-Motr.md
   - HLD-Configuration-Schema.md

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [x] Unit and System Tests are added

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

-----
[View rendered doc/HLD-Background-Scrub.md](https://github.com/swatid-seagate/cortx-motr/blob/new-md-file-upload/doc/HLD-Background-Scrub.md)
[View rendered doc/HLD-Capability-Motr.md](https://github.com/swatid-seagate/cortx-motr/blob/new-md-file-upload/doc/HLD-Capability-Motr.md)
[View rendered doc/HLD-Configuration-Schema.md](https://github.com/swatid-seagate/cortx-motr/blob/new-md-file-upload/doc/HLD-Configuration-Schema.md)

### CODE REVIEW

**Comment by chandradharraval** [comment]
@swatid-seagate, @madhavemuri  - Can you check above comments from @mehjoshi and get back?

**Comment by swatid-seagate** [comment]
> @swatid-seagate, @madhavemuri - Can you check above comments from @mehjoshi and get back?

I just converted the old (.rst) file to new format (.md). I think someone from Motr team should check for the stale data. Please inform me if any changes needed and I will take them up.

**Comment by huanghua78** [comment]
If there files are converted from rst files to md files, the original md files should be removed in this PR, and link to these files should be updated in `motr-design-doc-list.rst`.
`motr-design-doc-list.rst` should be converted to md format?

**Comment by swatid-seagate** [comment]
> If there files are converted from rst files to md files, the original md files should be removed in this PR, and link to these files should be updated in `motr-design-doc-list.rst`. `motr-design-doc-list.rst` should be converted to md format?

Hey Hua, once the new files are uploaded the olds files will be archived. This has already discussed with Rachel. For the references to 'motr-design-doc-list.rst': this is a task in progress. All the references will be updated as an when a new one is added.

**Comment by huanghua78** [comment]
> > If there files are converted from rst files to md files, the original md files should be removed in this PR, and link to these files should be updated in `motr-design-doc-list.rst`. `motr-design-doc-list.rst` should be converted to md format?
> 
> Hey Hua, once the new files are uploaded the olds files will be archived. This has already discussed with Rachel. For the references to 'motr-design-doc-list.rst': this is a task in progress. All the references will be updated as an when a new one is added.

Fine.

**Comment by mehjoshi** [comment]
> > > If there files are converted from rst files to md files, the original md files should be removed in this PR, and link to these files should be updated in `motr-design-doc-list.rst`. `motr-design-doc-list.rst` should be converted to md format?
> > 
> > 
> > Hey Hua, once the new files are uploaded the olds files will be archived. This has already discussed with Rachel. For the references to 'motr-design-doc-list.rst': this is a task in progress. All the references will be updated as an when a new one is added.
> 
> Fine. Please update the commit message to say that: These files are converted from .rst format to .md format

Hi @swatid-seagate , Please update the commit message as per the suggestion from @huanghua78

**Comment by swatid-seagate** [comment]
> > > > If there files are converted from rst files to md files, the original md files should be removed in this PR, and link to these files should be updated in `motr-design-doc-list.rst`. `motr-design-doc-list.rst` should be converted to md format?
> > > 
> > > 
> > > Hey Hua, once the new files are uploaded the olds files will be archived. This has already discussed with Rachel. For the references to 'motr-design-doc-list.rst': this is a task in progress. All the references will be updated as an when a new one is added.
> > 
> > 
> > Fine. Please update the commit message to say that: These files are converted from .rst format to .md format
> 
> Hi @swatid-seagate , Please update the commit message as per the suggestion from @huanghua78

OK

**Pull request merged**
