### PR TITLE
prov: fix install-build-deps on old CentOS versions

### PR DESCRIPTION
**Pull request by andriytk**
Old CentOS versions are not available at mirror.centos.org. Instead, vault.centos.org should be used for old versions. Otherwise, `install-build-deps` script would fail, like at https://github.com/Seagate/cortx-motr/issues/584.

Solution: update redhat_vault_repo_versions ansible variable with 7.7 and 7.8 CentOS versions, and don't skip vault-release tag at setup-node script (in order to use the vault repo versions).

### CODE REVIEW

**Comment by andriytk** [comment]
cc @chumakd

**Review by chumakd — APPROVED** [review]

**Comment by chumakd** [comment]
the only caveat is that enabling `vault-release` tag by default, for all versions of CentOS, might break yum repos of the current release, i.e. CentOS 7.9

its better to test the `install-build-deps` script on both 7.8 and 7.9 versions

**Comment by andriytk** [comment]
Checked on freshly installed CentOS 7.8 and 7.9 versions - works fine.

**Comment by hessio** [comment]
I have also tested this and it is working fine.

**Comment by huanghua78** [comment]
> I have also tested this and it is working fine.

Thanks for this conformation.

**Review by madhavemuri — APPROVED** [review]

**Review by huanghua78 — APPROVED** [review]

**Pull request merged**
