### PR TITLE
EOS-15930 Run jenkins tests with sock xprt

### PR DESCRIPTION
**Pull request by upendrapatwardhan**
This PR is just created to start a jenkins run. 
This PR should not be merged to main.

### CODE REVIEW

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212/>Motr#212</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>1</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>57</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/51motr-rmw target=_blank>04motr-single-node/51motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/50motr-rm-lock-cc-io target=_blank>04motr-single-node/50motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/33motr-st target=_blank>04motr-single-node/33motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/32m0t1fs-rconfc-fail-test target=_blank>04motr-single-node/32m0t1fs-rconfc-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/34sns-repair-1n-1f target=_blank>04motr-single-node/34sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/49motr-rpc-cancel target=_blank>04motr-single-node/49motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/04motr-single-node/48motr-raid0-io target=_blank>04motr-single-node/48motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/40motr-dgmode target=_blank>05motr-single-node/40motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/42motr-utils target=_blank>05motr-single-node/42motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/13sns-repair-quiesce target=_blank>05motr-single-node/13sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/45motr-sns-repair-N-1 target=_blank>05motr-single-node/45motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/11sns-multi-tests target=_blank>05motr-single-node/11sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/44motr-sns-repair target=_blank>05motr-single-node/44motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/14m0t1fs-fsync-test target=_blank>05motr-single-node/14m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/43motr-sync-replication target=_blank>05motr-single-node/43motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/38sns-abort-quiesce-test target=_blank>05motr-single-node/38sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/15m0t1fs-fwait-test target=_blank>05motr-single-node/15m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/18m0mount-test target=_blank>05motr-single-node/18m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit/05motr-single-node/10sns-single-tests target=_blank>05motr-single-node/10sns-single-tests</a></p></details></td></tr><tr><td>Total</td><td>63</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/212//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

**Comment by huanghua78** [comment]
@upendrapatwardhan @papan-singh 
Please work together to solve the UT failure cause.
Please note:
* As I have said in "EOS 14564 Independent Network Transport #216".
  1. the net/net.c:65 m0_net_init() is called first, before net/lnet/lnet_main.c:922 m0_net_lnet_init().
      So, the lnet module will set itself as default.
  2. The net/sock/sock.c will do the same: try to set itself as default.
  3. The last one wins.
  4. In the code, the default xprt will be over written and set to lnet.
  5. So, something like this is needed:
  ```
diff --git a/net/lnet/lnet_main.c b/net/lnet/lnet_main.c
index 78f6d72..6deeea7 100644
--- a/net/lnet/lnet_main.c
+++ b/net/lnet/lnet_main.c
@@ -922,7 +922,8 @@ M0_BASSERT(M0_NET_LNET_PID == LUSTRE_SRV_LNET_PID);
 M0_INTERNAL int m0_net_lnet_init(void)
 {
        m0_net_xprt_register(&m0_net_lnet_xprt);
-       m0_net_xprt_default_set(&m0_net_lnet_xprt);
+       if (m0_net_xprt_default_get() == NULL)
+               m0_net_xprt_default_set(&m0_net_lnet_xprt);
 
        return M0_RC(nlx_core_init());
 }
```


* There are a lot places with HARD-CODED LNET address.
  1. In this case, if we want to use sock xprt, we have to change the xprt for `cas_startup_cmd`:
  ```
diff --git a/cas/ut/client_ut.c b/cas/ut/client_ut.c
index 079e36b..8a6199e 100644
--- a/cas/ut/client_ut.c
+++ b/cas/ut/client_ut.c
@@ -81,7 +81,7 @@ enum { MAX_RPCS_IN_FLIGHT = 10 };
 static char *cas_startup_cmd[] = { "m0d", "-T", "linux",
                                 "-D", "cs_sdb", "-S", "cs_stob",
                                 "-A", "linuxstob:cs_addb_stob",
-                                "-e", "lnet:0@lo:12345:34:1",
+                                "-e", "sock:0@lo:12345:34:1",
                                 "-H", "0@lo:12345:34:1",
                                "-w", "10", "-F",
                                "-f", M0_UT_CONF_PROCESS,
```
Otherwise, it will use "lnet" xprt. A sock xprt can not communicate with a lnet xprt. The network protocol is not compatible with each other.


* There are many places:
```
apr-u520428l001:cortx-motr huanghua$ git grep "lnet:" 
cm/ut/cm.c:                             "-G", "lnet:0@lo:12345:34:1",
cm/ut/cm.c:                             "-e", "lnet:0@lo:12345:34:1",
conf/st:-A linuxstob:addb-stobs -e lnet:$M0D1_ENDPOINT -c $CONF_FILE -w 3"
conf/ut/common.h:#define SERVER_ENDPOINT      "lnet:" SERVER_ENDPOINT_ADDR
console/st/console-st.sh:           -w 10 -e lnet:$SERVER_EP_ADDR -H $SERVER_EP_ADDR \
console/st/server.c:#define ENDPOINT  "lnet:" SERVER_ENDPOINT_ADDR
console/ut/console.c:#define SERVER_ENDPOINT               "lnet:" SERVER_ENDPOINT_ADDR
dix/ut/client_ut.c:                             "-e", "lnet:0@lo:12345:34:1",
fdmi/plugin_dock.c:#define SERVER_ENDPOINT      "lnet:" SERVER_ENDPOINT_ADDR
fdmi/ut/filterc_ut.c:#define SERVER_ENDPOINT       "lnet:" SERVER_ENDPOINT_ADDR
ha/ut/note.c:#define SERVER_ENDPOINT       "lnet:" SERVER_ENDPOINT_ADDR
ioservice/ut/bulkio_common.c:   n = snprintf(ep, sizeof ep, "lnet:%s", server_ep_addr);
ioservice/ut/cob_foms.c:#define SERVER_ENDP                 "lnet:" SERVER_EP_ADDR
ioservice/ut/ios_buffer_pool.c:                         "-e", "lnet:0@lo:12345:34:1",
ioservice/ut/ios_buffer_pool.c:                         "-e", "lnet:0@lo:12345:34:1",
ioservice/ut/ios_buffer_pool.c:                         "-e", "lnet:0@lo:12345:34:1",
ioservice/ut/ios_buffer_pool.c:                         "-e", "lnet:0@lo:12345:34:1",
ioservice/ut/storage_dev_ut.c:  snprintf(full_ep, EP_MAX_LEN, "lnet:%s", confd_ep);
iscservice/ut/service_ut.c:#define SERVER_ENDPOINT      "lnet:" SERVER_ENDPOINT_ADDR
motr/conf.c:    static const char  xpt[] = "lnet:";
motr/setup.c:"           e.g. lnet:172.18.50.40@o2ib1:12345:34:1\n"
motr/setup.c:"        -e lnet:172.18.50.40@o2ib1:12345:34:1 \\\n"
motr/setup.h:                   "-e", "lnet:172.18.50.40@o2ib1:12345:34:1",
motr/setup.h:   CS_MAX_EP_ADDR_LEN = 86 /* "lnet:" + M0_NET_LNET_XEP_ADDR_LEN */
motr/setup.h:M0_BASSERT(CS_MAX_EP_ADDR_LEN >= sizeof "lnet:" + M0_NET_LNET_XEP_ADDR_LEN);
motr/st/m0d-fatal:        -A linuxstob:$path/addb-stobs -e lnet:$M0D1_ENDPOINT
motr/st/m0d-fatal:        -A linuxstob:$path/addb-stobs -e lnet:$M0D2_ENDPOINT
motr/ut/cs_ut_main.c:#define SERVER_ENDPOINT      "lnet:" SERVER_ENDPOINT_ADDR
motr/ut/cs_ut_main.c:                                "-e", "lnet:asdad:asdsd:sadasd",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@o2ib1:12345:34:1",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@o2ib1:12345:34:1",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@tcp:12345:30:101",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@o2ib0:12345:34:101",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@tcp:12345:30:101",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@o2ib0:12345:34:101",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@o2ib1:12345:30:101",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@o2ib1:12345:30:101",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@tcp:12345:30:101",
motr/ut/cs_ut_main.c:                                "-e", "lnet:172.18.50.40@tcp:12345:32:105",
motr/ut/cs_ut_main.c:                                "-e", "lnet:asdad:asdsd:sadasd",
motr/ut/idx_dix.c:                                "-e", "lnet:0@lo:12345:34:1",
net/lnet/linux_kernel/klnet_core.h:      * 2.2.54-55-ga096d85 "LU-56 lnet: allow to create EQ with zero eq_size"
net/lnet/linux_kernel/klnet_utils.c:     * commit v2_2_57-10-g75a8f4b "LU-56 lnet: split lnet_commit_md and
reqh/ut/service_ctx.c:                  "-e", "lnet:0@lo:12345:34:1",
rm/ut/rm_service.c:#define SERVER_ENDPOINT      "lnet:" SERVER_ENDPOINT_ADDR
rpc/ub/ub.c:#  define SERVER_ENDPOINT      "lnet:" SERVER_ENDPOINT_ADDR
rpc/ut/clnt_srv_ctx.c:#define SERVER_ENDPOINT       "lnet:" SERVER_ENDPOINT_ADDR
scripts/install/usr/libexec/cortx-motr/motr-server:        service_ep="lnet:$ha_ep"
scripts/install/usr/libexec/cortx-motr/motr-server:        service_ep="lnet:${MOTR_M0D_EP:-$(m0_get_ep_of $service)}"
sns/cm/repair/ut/cp_common.c:                             "-G", "lnet:0@lo:12345:34:1",
sns/cm/repair/ut/cp_common.c:                                  "-e", "lnet:0@lo:12345:34:1",
sns/cm/repair/ut/cp_common.c:                                "-G", "lnet:0@lo:12345:34:1",
sns/cm/repair/ut/cp_common.c:                                "-e", "lnet:0@lo:12345:34:1",
spiel/st/m0t1fs_spiel_st.sh:    -A linuxstob:$path/addb-stobs -e lnet:$M0D1_ENDPOINT\
spiel/st/m0t1fs_spiel_st.sh:    -A linuxstob:$path/addb-stobs -e lnet:$M0D2_ENDPOINT -c $CONF_FILE\
spiel/st/m0t1fs_spiel_st.sh:    -A linuxstob:$path/addb-stobs -e lnet:$M0D2_ENDPOINT -c $CONF_FILE\
spiel/st/spiel_multiple_confd.sh:    -A linuxstob:$path/addb-stobs -e lnet:${!ep}\
spiel/st/spiel_multiple_confd.sh:    -A linuxstob:$path/addb-stobs -e lnet:${!ep}\
spiel/ut/spiel_ut_common.c:     snprintf(full_ep, EP_MAX_LEN, "lnet:%s", ha_ep);
spiel/ut/spiel_ut_common.h:#define SERVER_ENDPOINT      "lnet:" SERVER_ENDPOINT_ADDR
sss/st:-A linuxstob:sss_st-addb.stob -e lnet:$(endpoint $SERVER_TMID)
sss/ut/sss_ut.c:#define SERVER_ENDPOINT       "lnet:" SERVER_ENDPOINT_ADDR
st/m0mount-fail:-A linuxstob:addb-stobs -e lnet:$M0D1_ENDPOINT -c $conf_file -w 3"
st/stob_domain_recreate_on_corruption.sh:    -A linuxstob:$path/addb-stobs -e lnet:$ep\
utils/m0reportbug:        ## /var/motr/ios1/core.1271: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'm0d -e lnet:10.22.192.32@tcp:12345:42:401 -f <0x7200000000000001:4> -T ad -D db'

```
and 

```
apr-u520428l001:cortx-motr huanghua$ git grep "\<XPT\>"
m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh:XPT=lnet
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:            opts="$common_opts -T linux -e $XPT:${CONFD_EP%:*:*}:$MKFS_PORTAL:1\
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:            opts="$common_opts -f $proc_fid -T linux -e $XPT:$CONFD_EP \
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:            opts="$common_opts -T ad -e $XPT:${lnet_nid}:${HA_EP%:*:*}:$MKFS_PORTAL:1 \
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:                    $common_opts -e $XPT:${lnet_nid}:${MDSEP[$i]%:*:*}:$MKFS_PORTAL:$tmid \
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:                    $common_opts -e $XPT:${lnet_nid}:${IOSEP[$i]%:*:*}:$MKFS_PORTAL:$tmid  $FI_OPTS \
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:                    $common_opts -e $XPT:${lnet_nid}:${IOS_PVER2_EP%:*:*}:$MKFS_PORTAL:$tmid  $FI_OPTS \
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:            opts="$common_opts -T ad -e $XPT:${lnet_nid}:$HA_EP \
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:                    $common_opts -e $XPT:${lnet_nid}:${MDSEP[$i]} \
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:                    $common_opts -e $XPT:${lnet_nid}:${IOSEP[$i]} \
m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh:                    $common_opts -e $XPT:${lnet_nid}:$IOS_PVER2_EP \
utils/m0mount:XPT=lnet
utils/m0mount:                  mkfs $DIR "-T linux" "-c $CONF_FILE" "-e $XPT:$CONFD_EP" || return 1
utils/m0mount:-e $XPT:$CONFD_EP -c $CONF_FILE \
utils/m0mount:                  mkfs $DIR "-T linux" "-c $CONF_FILE" "-e $XPT:$HA_EP" || return 1
utils/m0mount:-w $POOL_WIDTH -e $XPT:$HA_EP -c $CONF_FILE \
utils/m0mount:                  mkfs "$DIR" "-T linux" "-c $CONF_FILE" "-e $XPT:$MDS_EP" || return 1
utils/m0mount:-w $POOL_WIDTH -e $XPT:$MDS_EP -H $HA_EP -c $CONF_FILE \
utils/m0mount:          mkfs "$DDIR" "$STOB_PARAMS" "-H $HA_EP" "-e $XPT:$EP" || return 1
utils/m0mount:-w $POOL_WIDTH -e $XPT:$EP $SNAME $XPT_SETUP" >> ${SLOG}$I.log &
apr-u520428l001:cortx-motr huanghua$ 

```


If we want to use "sock" xprt, we must fix them.

* And here:
```
254 static bool cs_endpoint_is_duplicate(const struct m0_reqh_context *rctx,
 255                                      const struct m0_net_xprt *xprt,
 256                                      const char *ep)
 257 {
 258         static int (*cmp[])(const char *s1, const char *s2) = {
 259                 strcmp,
 260                 m0_net_lnet_ep_addr_net_cmp
 261         };
 262         struct cs_endpoint_and_xprt *ex;
 263         bool                         seen = false;
 264 
 265         M0_PRE(reqh_context_invariant(rctx) && ep != NULL);
 266 
 267         m0_tl_for(cs_eps, &rctx->rc_eps, ex) {
 268                 M0_ASSERT(cs_endpoint_and_xprt_bob_check(ex));
 269                 if (cmp[!!m0_streq(xprt->nx_name, "lnet")](ex->ex_endpoint,
 270                                                            ep) == 0 &&
 271                     m0_streq(ex->ex_xprt, xprt->nx_name)) {
 272                         if (seen)
 273                                 return true;
 274                         else
 275                                 seen = true;
 276                 }
 277         } m0_tl_endfor;
 278 
 279         return false;
 280 }
                                           
```

**Comment by huanghua78** [comment]
In this test, actually, because m0_net_lnet_init() called m0_net_xprt_default_set(), the default xprt is still **LNET**.


In this failed UT, the server is using LNET, while the client is using SOCK. So, the UT failed.

**Comment by huanghua78** [comment]
I'll close this PR. When ready to test sock xprt, we can open this or create a new one.

**Pull request closed without merging**
