### PR TITLE
EOS-25988: [F-53B]Motr: Adopt best compression format for Motr support bundle

### PR DESCRIPTION
**Pull request by papan-singh**
…t bundle.

Create .tar.gz archive as best compression techniques.

Signed-off-by: Papan Kumar Singh <papan.kumarsingh@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by papan-singh** [comment]
tested in k8s env
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 ~]# /opt/seagate/cortx/motr/libexec/m0reportbug-bundler SBbw5f7n9i /var/log/support_bundle --duration "2020-09-06T05:30:00P5DT3H3S" --size_limit 100MB --services All --binlogs false --coredumps false --stacktrace false
probes... OK
misc_files... OK
backtraces_live... OK
coredump_live... *WARNING* ## live core are not collected on kvm ##
OK
backtraces_cores... OK
binaries... OK
m0traces... OK
addb... OK
addb-files... OK
systemd_journal... No journal files were found.
OK
sysrq_info... *WARNING* /proc/sysrq-trigger is read-only. Won't be able to collect system information.
OK
*WARNING* /var/crash/: no such directory
*WARNING* /var/log/crash/: no such directory
*WARNING* /var/log/seagate/motr/tmpspace/: no such directory
m0traces /opt/seagate/cortx/motr/libexec... OK
m0traces /etc/cortx/log/motr/eb3be881ffed45378cd8278d085b6182/trace... OK (1m3s)
addb-files /etc/cortx/log/motr/eb3be881ffed45378cd8278d085b6182/addb... OK (0m58s)
Please attach these files to the bug report:
  m0reportbug-data.tar.gz
  m0reportbug-cores.tar.gz
  m0reportbug-traces.tar.gz
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 ~]# cd /var/log/support_bundle
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 support_bundle]# ls
motr
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 support_bundle]# cd motr/
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# ls
motr_SBbw5f7n9i.tar
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# tar -xvf motr_SBbw5f7n9i.tar
cortx-data-headless-svc-ssc-vm-rhev4-1762/
cortx-data-headless-svc-ssc-vm-rhev4-1762/_m0reportbug-bundler.stderr
cortx-data-headless-svc-ssc-vm-rhev4-1762/m0reportbug-data.tar.gz
cortx-data-headless-svc-ssc-vm-rhev4-1762/m0reportbug-cores.tar.gz
cortx-data-headless-svc-ssc-vm-rhev4-1762/m0reportbug-traces.tar.gz
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# cd cortx-data-headless-svc-ssc-vm-rhev4-1762/
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 cortx-data-headless-svc-ssc-vm-rhev4-1762]# ls
_m0reportbug-bundler.stderr  m0reportbug-cores.tar.gz  m0reportbug-data.tar.gz  m0reportbug-traces.tar.gz
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 cortx-data-headless-svc-ssc-vm-rhev4-1762]#
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 cortx-data-headless-svc-ssc-vm-rhev4-1762]# tar -xvf m0reportbug-data.tar.gz
m0reportbug-data/
m0reportbug-data/addb_files/
m0reportbug-data/addb_files/var/
m0reportbug-data/addb_files/var/motr/
m0reportbug-data/addb_files/etc/
m0reportbug-data/addb_files/etc/cortx/
m0reportbug-data/addb_files/etc/cortx/log/
m0reportbug-data/addb_files/etc/cortx/log/motr/
m0reportbug-data/addb_files/etc/cortx/log/motr/eb3be881ffed45378cd8278d085b6182/
m0reportbug-data/addb_files/etc/cortx/log/motr/eb3be881ffed45378cd8278d085b6182/addb/
m0reportbug-data/addb_files/etc/cortx/log/motr/eb3be881ffed45378cd8278d085b6182/addb/m0d_addb__addb.xz
m0reportbug-data/root-misc/
m0reportbug-data/root-misc/etc/
m0reportbug-data/root-misc/etc/motr/
m0reportbug-data/root-misc/etc/motr/confd.xc
m0reportbug-data/root-misc/etc/sysconfig/
m0reportbug-data/root-misc/etc/sysconfig/motr
m0reportbug-data/root-misc/etc/sysconfig/motr-free-space-monitor
m0reportbug-data/systemd-journal.xz
m0reportbug-data/m0reportbug.txt

**Comment by gargpalak048** [comment]
@papan-singh  As you pasted the testing results,
https://github.com/Seagate/cortx-motr/pull/1290#issuecomment-986526368
I can see, the final output file '.tar', can we compress the output file to tar.gz

> [root@cortx-data-headless-svc-ssc-vm-rhev4-1762 support_bundle]# cd motr/
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# ls
**motr_SBbw5f7n9i.tar**

**Comment by papan-singh** [comment]
> @papan-singh As you pasted the testing results, [#1290 (comment)](https://github.com/Seagate/cortx-motr/pull/1290#issuecomment-986526368) I can see, the final output file '.tar', can we compress the output file to tar.gz
> 
> > [root@cortx-data-headless-svc-ssc-vm-rhev4-1762 support_bundle]# cd motr/
> > [root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# ls
> > **motr_SBbw5f7n9i.tar**

# The archives generated by `m0reportbug` are already compressed (.tar.gz).
# It would be pointless to compress them again.
tar --remove-files -cf "${COMPONENT}_${bundle_id}.tar" $HOSTNAME

**Comment by cdeshmukh** [comment]
Good catch @gargpalak048 

@papan-singh I see internal archives in tar.gz, which is good, however final component support bundle should also be compressed using tar.gz only
> cortx-data-headless-svc-ssc-vm-rhev4-1762/m0reportbug-data.tar.gz
cortx-data-headless-svc-ssc-vm-rhev4-1762/m0reportbug-cores.tar.gz
cortx-data-headless-svc-ssc-vm-rhev4-1762/m0reportbug-traces.tar.gz

**Comment by cdeshmukh** [comment]
> # It would be pointless to compress them again.

Sure compressing tar.gz further wont help much, but it would help to keep consistency.

**Comment by papan-singh** [comment]
Tested the patch in k8s env
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# ls -R /var/log/support_bundle
/var/log/support_bundle:
motr

/var/log/support_bundle/motr:
motr_SBbw5f7n9i.tar.gz
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# cd /var/log/support_bundle/motr/
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# tar -xvf motr_SBbw5f7n9i.tar.gz
cortx-data-headless-svc-ssc-vm-rhev4-1762/
cortx-data-headless-svc-ssc-vm-rhev4-1762/_m0reportbug-bundler.stderr
cortx-data-headless-svc-ssc-vm-rhev4-1762/m0reportbug-data.tar.gz
cortx-data-headless-svc-ssc-vm-rhev4-1762/m0reportbug-cores.tar.gz
cortx-data-headless-svc-ssc-vm-rhev4-1762/m0reportbug-traces.tar.gz
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# ls
cortx-data-headless-svc-ssc-vm-rhev4-1762  motr_SBbw5f7n9i.tar.gz
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 motr]# cd cortx-data-headless-svc-ssc-vm-rhev4-1762/
[root@cortx-data-headless-svc-ssc-vm-rhev4-1762 cortx-data-headless-svc-ssc-vm-rhev4-1762]# ls
_m0reportbug-bundler.stderr  m0reportbug-cores.tar.gz  m0reportbug-data.tar.gz  m0reportbug-traces.tar.gz

**Review by yeshpal-jain-seagate — COMMENTED** [review]
Already the final compression that we are using is tar.gz, 
what is the difference in compression time/compression size we have if we run m0traces also with /without xz

**Comment by cdeshmukh** [comment]
> Already the final compression that we are using is tar.gz, what is the difference in compression time/compression size we have if we run m0traces also with /without xz

general xz vs tgz comparison details were captured here
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/802456195/Explore+Compression+Techniques+for+Support+Bundle+Optimization

**Review by cdeshmukh — APPROVED** [review]

**Review by gargpalak048 — APPROVED** [review]
LGTM

**Review by yatin-mahajan — APPROVED** [review]
Looks good to me.

**Comment by mehjoshi** [comment]
retest this please

**Comment by mehjoshi** [comment]
retest this please

**Comment by papan-singh** [comment]
> retest this please

Tested on 1 Node VM setup
/opt/seagate/cortx/motr/libexec/m0reportbug-bundler SBbw5f7n9i /var/log/support_bundle --duration "2020-09-06T05:30:00P5DT3H3S" --size_limit 100MB \
--services All --binlogs false --coredumps false --stacktrace false
WARNING VERSION must be updated
probes... OK
misc_files... OK
backtraces_live... OK
coredump_live... *WARNING* ## live core are not collected on kvm ##
OK
backtraces_cores... OK
binaries... OK
m0traces... OK (3m50s)
addb... m0addb2dump: Cannot initialise iterator: -71: No such file or directory
OK (13m37s)
addb-files... OK (2m42s)
systemd_journal... OK (0m27s)
sysrq_info... OK
backtraces_core /var/crash/... OK
backtraces_core /var/log/crash/... OK
backtraces_core /var/log/seagate/motr/tmpspace/... OK
m0traces /opt/seagate/cortx/motr/libexec... OK
WARNING : no such directory
WARNING : no such directory
'/var/log/motr-rpm-conf-update.log' -> 'm0reportbug-data/motr-rpm-conf-update.log'
Please attach these files to the bug report:
  m0reportbug-data.tar.gz
  m0reportbug-cores.tar.gz
  m0reportbug-traces.tar.gz
[root@ssc-vm-rhev4-1763 ~]# ls /var/log/support_bundle/motr/
motr_SBbw5f7n9i.tar.gz

**Pull request merged**
