### PR TITLE
EOS-16760: configure with variable rpm version

### PR DESCRIPTION
**Pull request by bansisoni**
- configure rpm version with -v option. Example:  ./autogen.sh -v 1.2.4
- without any argument, autogen.sh will generate configure with default rpm version in configure.ac
- rpm version must be ^([0-9]+)\.([0-9]+)\.([0-9]+)$ . Example: 1.23.1, 2.0.24
- help message added. Example:  ./autogen.sh -h

Signed-off-by: Bansidhar Soni <bansidhar.soni@seagate.com>

### CODE REVIEW

**Comment by huanghua78** [comment]
```
57 # E.g., LT_VERSION=1:1:0 results in motr/.libs/libmotr.so.1.0.1 file.
  58 #
  59 # See also
  60 # https://www.gnu.org/software/libtool/manual/libtool.html#Libtool-versioning
  61 AC_SUBST([LT_VERSION], [M0_VERSION_MAJOR:M0_VERSION_MINOR:M0_VERSION_PATCH])
  62 
  63 # the following variables are only for internal use within this configure script
  64 # external scripts should use collection of variables, which is automatically
  65 # provided by autoconf:
  66 #
  67 #    @srcdir@
  68 #    @top_srcdir@
  69 #    @abs_top_srcdir@
  70 #    @builddir@
  71 #    @top_builddir@
  72 #    @abs_top_builddir@
  73 #
  74 SRCDIR="$srcdir"
  75 ABS_SRCDIR="$(cd $srcdir; pwd)"
  76 ABS_BUILDDIR="$(pwd)"
  77 AC_SUBST([ABS_BUILDDIR])
  78 
  79 AC_SUBST([M0_VERSION_CODE],
  80          ["$(( (M0_VERSION_MAJOR << 24) + (M0_VERSION_MINOR << 16) + (M0_VERSION_PATCH << 8) ))U"]
  81 )

```

There are two more places:
 LT_VERSION
and 
M0_VERSION_CODE

They also need to be taken care of.

**Comment by huanghua78** [comment]
```
sh autogen.sh -v 12.34.56

./configure

make

[root@cmu cortx-motr]# ll motr/.libs/libmotr.so*
lrwxrwxrwx 1 501 games       16 Feb 12 06:00 motr/.libs/libmotr.so -> libmotr.so.1.0.0
lrwxrwxrwx 1 501 games       16 Feb 12 06:00 motr/.libs/libmotr.so.1 -> libmotr.so.1.0.0
-rwxr-xr-x 1 501 games 31715832 Feb 12 06:00 motr/.libs/libmotr.so.1.0.0
[root@cmu cortx-motr]# 
[root@cmu cortx-motr]# 
[root@cmu cortx-motr]# 
[root@cmu cortx-motr]# 
[root@cmu cortx-motr]# 
[root@cmu cortx-motr]# 
[root@cmu cortx-motr]# 
[root@cmu cortx-motr]# head configure.ac 
# Motr version
m4_define([M0_VERSION_MAJOR],[1])
m4_define([M0_VERSION_MINOR],[0])
m4_define([M0_VERSION_PATCH],[0])
m4_define([M0_VERSION],[12.34.56])

#
# Autoconf/Automake/Libtool configuration --------------------------------- {{{1
#

[root@cmu cortx-motr]# 


vim motr/version_macros.h
23 #pragma once
 24 
 25 #ifndef __MOTR_MOTR_VERSION_MACROS_H__
 26 #define __MOTR_MOTR_VERSION_MACROS_H__
 27 
 28 
 29 #define M0_VERSION(a,b,c) (((a) << 24) + ((b) << 16) + ((c) << 8))
 30 
 31 #define M0_VERSION_CODE  16777216U
 32 
 33 #define M0_VERSION_STRING         "12.34.56"
 34 #define M0_VERSION_GIT_REV_ID     "c1f5fbcf3589582c60b0b1a2c7509e24582178e6"
 35 #define M0_VERSION_GIT_DESCRIBE   "sage-base-1.0-203-gc1f5fbc-dirty"
 36 #define M0_VERSION_GIT_BRANCH     "EOS-16760"
 37 #define M0_VERSION_BUILD_HOST     "cmu"
 38 #define M0_VERSION_BUILD_USER     "root"
 39 #define M0_VERSION_BUILD_TIME     "Fri Feb 12 10:54:11 UTC 2021"
 40 #define M0_VERSION_BUILD_GCC      "gcc version 4.8.5 20150623 (Red Hat 4.8.5-39)  "
 41 #define M0_VERSION_BUILD_KERNEL   "3.10.0-1062.el7.x86_64"
"motr/version_macros.h" 64L, 3268C                                                                                                  1,1           Top

```

Please the version number in the libmotr.so.1.0.0
and the 
 31 #define M0_VERSION_CODE  16777216U

**Comment by huanghua78** [comment]
What about this:
```
apr-u520428l001:cortx-motr huanghua$ git diff autogen.sh 
diff --git a/autogen.sh b/autogen.sh
index d51afa6f..8318df5f 100755
--- a/autogen.sh
+++ b/autogen.sh
@@ -33,8 +33,12 @@ while getopts "hv:" arg; do
       echo RPM version: $version
       if [[ $version =~ $regex ]]
       then
-        sed -i "/m4_define(\[M0_VERSION],/c\m4_define([M0_VERSION],[$version])"\
-        configure.ac
+        MAJOR=$(echo $version | cut -d "." -f 1)
+        MINOR=$(echo $version | cut -d "." -f 2)
+        PATCH=$(echo $version | cut -d "." -f 3)
+        sed -i "/m4_define(\[M0_VERSION_MAJOR],/c\m4_define([M0_VERSION_MAJOR],[$MAJOR])" configure.ac
+        sed -i "/m4_define(\[M0_VERSION_MINOR],/c\m4_define([M0_VERSION_MINOR],[$MINOR])" configure.ac
+        sed -i "/m4_define(\[M0_VERSION_PATCH],/c\m4_define([M0_VERSION_PATCH],[$PATCH])" configure.ac
       else
         echo "RPM version must be numeric with two dot(.). Example: 1.3.20"
         exit 1

```


But with this patch, we will get such error:
```
[root@cmu cortx-motr]# sh autogen.sh -v 1.3.20
...
[root@cmu cortx-motr]# ./configure 
..
[root@cmu cortx-motr]# make
...
  CC       stob/motr_libmotr_la-ad_private_xc.lo
  CC       stob/motr_libmotr_la-ioq_error_xc.lo
  CC       stob/motr_libmotr_la-stob_xc.lo
  CC       stats/motr_libmotr_la-stats_fops_xc.lo
  CC       reqh/ut/motr_libmotr_la-io_fop_xc.lo
  CC       reqh/ut/motr_libmotr_la-service_xc.lo
  CCLD     motr/libmotr.la
libtool: link: AGE `20' is greater than the current interface number `1'
libtool: link: `1:3:20' is not valid version information
make[2]: *** [motr/libmotr.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
[root@cmu cortx-motr]# 


```


It seems we need to follow the "7.3 Updating library version information" 
https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

```
If you want to use libtool’s versioning system, then you must specify the version information to libtool using the -version-info flag during link mode (see Link mode).

This flag accepts an argument of the form ‘current[:revision[:age]]’. So, passing -version-info 3:12:1 sets current to 3, revision to 12, and age to 1.

If either revision or age are omitted, they default to 0. Also note that age must be less than or equal to the current interface number.

Here are a set of rules to help you update your library version information:

Start with version information of ‘0:0:0’ for each libtool library.
Update the version information only immediately before a public release of your software. More frequent updates are unnecessary, and only guarantee that the current interface number gets larger faster.
If the library source code has changed at all since the last update, then increment revision (‘c:r:a’ becomes ‘c:r+1:a’).
If any interfaces have been added, removed, or changed since the last update, increment current, and set revision to 0.
If any interfaces have been added since the last public release, then increment age.
If any interfaces have been removed or changed since the last public release, then set age to 0.
```

**Comment by bansisoni** [comment]
Few outputs for different version number:
```
./autogen.sh -v 3.12.2
[root@ssc-vm-1399 cortx-motr]# rpm -qlpv  /root/rpmbuild/RPMS/x86_64/cortx-motr-3.12.2-1_gitc1f5fbc_3.10.0_1127.el7.x86_64.rpm|grep motr.so.
-r--r--r--    1 root    root                 24845224 Feb 14 03:01 /usr/lib/debug/usr/lib64/libmotr.so.1.2.12.debug
lrwxrwxrwx    1 root    root                       23 Feb 14 03:01 /usr/lib/debug/usr/lib64/libmotr.so.1.debug -> libmotr.so.1.2.12.debug
lrwxrwxrwx    1 root    root                       23 Feb 14 03:01 /usr/lib/debug/usr/lib64/libmotr.so.debug -> libmotr.so.1.2.12.debug
-r--r--r--    1 root    root                   106040 Feb 14 03:01 /usr/lib/debug/usr/lib64/python2.7/site-packages/motr.so.debug
lrwxrwxrwx    1 root    root                       17 Feb 14 03:01 /usr/lib64/libmotr.so -> libmotr.so.1.2.12
lrwxrwxrwx    1 root    root                       17 Feb 14 03:01 /usr/lib64/libmotr.so.1 -> libmotr.so.1.2.12
-rwxr-xr-x    1 root    root                  7355520 Feb 14 03:01 /usr/lib64/libmotr.so.1.2.12

./autogen.sh -v 3.12.3
[root@ssc-vm-1399 cortx-motr]# rpm -qlpv /root/rpmbuild/RPMS/x86_64/cortx-motr-3.12.3-1_gitc1f5fbc_3.10.0_1127.el7.x86_64.rpm|grep motr.so.
-r--r--r--    1 root    root                 24845224 Feb 14 03:26 /usr/lib/debug/usr/lib64/libmotr.so.0.3.12.debug
lrwxrwxrwx    1 root    root                       23 Feb 14 03:26 /usr/lib/debug/usr/lib64/libmotr.so.0.debug -> libmotr.so.0.3.12.debug
lrwxrwxrwx    1 root    root                       23 Feb 14 03:26 /usr/lib/debug/usr/lib64/libmotr.so.debug -> libmotr.so.0.3.12.debug
-r--r--r--    1 root    root                   106040 Feb 14 03:26 /usr/lib/debug/usr/lib64/python2.7/site-packages/motr.so.debug
lrwxrwxrwx    1 root    root                       17 Feb 14 03:26 /usr/lib64/libmotr.so -> libmotr.so.0.3.12
lrwxrwxrwx    1 root    root                       17 Feb 14 03:26 /usr/lib64/libmotr.so.0 -> libmotr.so.0.3.12
-rwxr-xr-x    1 root    root                  7355520 Feb 14 03:26 /usr/lib64/libmotr.so.0.3.12

./autogen.sh -v 3.12.1
[root@ssc-vm-1399 cortx-motr]# rpm -qlpv /root/rpmbuild/RPMS/x86_64/cortx-motr-3.12.1-1_gitc1f5fbc_3.10.0_1127.el7.x86_64.rpm|grep motr.so.
-r--r--r--    1 root    root                 24845224 Feb 14 03:44 /usr/lib/debug/usr/lib64/libmotr.so.2.1.12.debug
lrwxrwxrwx    1 root    root                       23 Feb 14 03:44 /usr/lib/debug/usr/lib64/libmotr.so.2.debug -> libmotr.so.2.1.12.debug
lrwxrwxrwx    1 root    root                       23 Feb 14 03:44 /usr/lib/debug/usr/lib64/libmotr.so.debug -> libmotr.so.2.1.12.debug
-r--r--r--    1 root    root                   106040 Feb 14 03:44 /usr/lib/debug/usr/lib64/python2.7/site-packages/motr.so.debug
lrwxrwxrwx    1 root    root                       17 Feb 14 03:44 /usr/lib64/libmotr.so -> libmotr.so.2.1.12
lrwxrwxrwx    1 root    root                       17 Feb 14 03:44 /usr/lib64/libmotr.so.2 -> libmotr.so.2.1.12
-rwxr-xr-x    1 root    root                  7355520 Feb 14 03:44 /usr/lib64/libmotr.so.2.1.12
```

**Comment by bansisoni** [comment]
As commented by @huanghua78 , 

> This flag accepts an argument of the form **‘current[:revision[:age]]’**. So, passing -version-info 3:12:1 sets current to 3, revision to 12, and age to 1.
> 
> **If either revision or age are omitted, they default to 0. Also note that age must be less than or equal to the current interface number.**

we will get below error if patch version number is greater than major version number. 
```
libtool: link: AGE `20' is greater than the current interface number `1'
libtool: link: `1:3:20' is not valid version information
```

**Review by madhavemuri — APPROVED** [review]

**Comment by huanghua78** [comment]
Hello @bansisoni, are you trying to figure out solutions for the known issues?
Or do we need some guidance from some exports on this topic?

**Comment by bansisoni** [comment]
@huanghua78  As per my understanding, the M0_VERSION is the release version which should not relate with LT_VERSION (library version). If library interface is changed/add/remove then and then only we need to change LT_VERSION  version macro value. We can make different macro for LT_VERSION which is independent from rpm/release version.
https://github.com/Seagate/cortx-motr/blob/90a5376540d446914447b6e22d776c04560ce70c/configure.ac#L61

Let me know you thoughts. @huanghua78 @madhavemuri

**Comment by huanghua78** [comment]
> @huanghua78 As per my understanding, the M0_VERSION is the release version which should not relate with LT_VERSION (library version). If library interface is changed/add/remove then and then only we need to change LT_VERSION version macro value. We can make different macro for LT_VERSION which is independent from rpm/release version.
> https://github.com/Seagate/cortx-motr/blob/90a5376540d446914447b6e22d776c04560ce70c/configure.ac#L61
> 
> Let me know you thoughts. @huanghua78 @madhavemuri

I have changed the following:

```
 AC_SUBST([LT_VERSION], [M0_VERSION_MAJOR:M0_VERSION_MINOR:0]) 

```

It passed various testing.
Please check.

**Review by huanghua78 — APPROVED** [review]

**Comment by huanghua78** [comment]
Hello @madhavemuri , please review this again.

**Review by madhavemuri — APPROVED** [review]

**Comment by cortx-admin** [comment]
<h1>Jenkins CI Result : <a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288/>Motr#288</a></h1><h2>Motr Test Summary</h2><table><tr><th>Test Result</th><th>Count</th><th>Info</tr><tr><td>:x:Failed</td><td>1</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/32m0t1fs-rconfc-fail-test target=_blank>04motr-single-node/32m0t1fs-rconfc-fail-test</a></p></details></td></tr><tr><td>:checkered_flag:Skipped</td><td>5</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/37protocol target=_blank>01motr-single-node/37protocol</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/31motr-sys-kvs-kernel-test target=_blank>04motr-single-node/31motr-sys-kvs-kernel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/07multi-client-tests target=_blank>05motr-single-node/07multi-client-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/39mount-fail target=_blank>05motr-single-node/39mount-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/12sns-cc-io-tests target=_blank>05motr-single-node/12sns-cc-io-tests</a></p></details></td></tr><tr><td>:heavy_check_mark:Passed</td><td>58</td><td><details><summary>:file_folder:</summary><p><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/46m0crate target=_blank>01motr-single-node/46m0crate</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/01kernel-tests target=_blank>01motr-single-node/01kernel-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/00userspace-tests target=_blank>01motr-single-node/00userspace-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/03initscript-tests target=_blank>01motr-single-node/03initscript-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/30hagen-test target=_blank>01motr-single-node/30hagen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/29confgen-test target=_blank>01motr-single-node/29confgen-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/35m0singlenode target=_blank>01motr-single-node/35m0singlenode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/04net-tests target=_blank>01motr-single-node/04net-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/05rpcping-tests target=_blank>01motr-single-node/05rpcping-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/28motr-sys-kvs-test target=_blank>01motr-single-node/28motr-sys-kvs-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/06console-tests target=_blank>01motr-single-node/06console-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/01motr-single-node/52singlenode-sanity target=_blank>01motr-single-node/52singlenode-sanity</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/20pool-version-test target=_blank>02motr-single-node/20pool-version-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/21spiel-test target=_blank>02motr-single-node/21spiel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/47motr-tests-user-kernel target=_blank>02motr-single-node/47motr-tests-user-kernel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/09poolmach-tests target=_blank>02motr-single-node/09poolmach-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/41motr-conf-update target=_blank>02motr-single-node/41motr-conf-update</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/08degraded-mode-tests target=_blank>02motr-single-node/08degraded-mode-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/24m0d-fsync-test target=_blank>02motr-single-node/24m0d-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/02system-tests target=_blank>02motr-single-node/02system-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/22rpc-cancel-test target=_blank>02motr-single-node/22rpc-cancel-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/53clusterusage-alert target=_blank>02motr-single-node/53clusterusage-alert</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/23m0d-signal-test target=_blank>02motr-single-node/23m0d-signal-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/02motr-single-node/51kem target=_blank>02motr-single-node/51kem</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/54sns-repair-motr-1f target=_blank>03motr-single-node/54sns-repair-motr-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/59sns-repair-motr-abort target=_blank>03motr-single-node/59sns-repair-motr-abort</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/17sss-st-test target=_blank>03motr-single-node/17sss-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/58sns-repair-motr-ios-fail target=_blank>03motr-single-node/58sns-repair-motr-ios-fail</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/60sns-repair-motr-abort-quiesce target=_blank>03motr-single-node/60sns-repair-motr-abort-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/55sns-repair-motr-1n-1f target=_blank>03motr-single-node/55sns-repair-motr-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/56sns-repair-motr-mf target=_blank>03motr-single-node/56sns-repair-motr-mf</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/61spiel-multi-confd target=_blank>03motr-single-node/61spiel-multi-confd</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/16conf-st-test target=_blank>03motr-single-node/16conf-st-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/57sns-repair-motr-1k-1f target=_blank>03motr-single-node/57sns-repair-motr-1k-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/03motr-single-node/36spare-reservation target=_blank>03motr-single-node/36spare-reservation</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/51motr-rmw target=_blank>04motr-single-node/51motr-rmw</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/50motr-rm-lock-cc-io target=_blank>04motr-single-node/50motr-rm-lock-cc-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/25spiel-sns-repair-test target=_blank>04motr-single-node/25spiel-sns-repair-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/33motr-st target=_blank>04motr-single-node/33motr-st</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/19sns-abort-test target=_blank>04motr-single-node/19sns-abort-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/34sns-repair-1n-1f target=_blank>04motr-single-node/34sns-repair-1n-1f</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/26spiel-sns-repair-quiesce-test target=_blank>04motr-single-node/26spiel-sns-repair-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/49motr-rpc-cancel target=_blank>04motr-single-node/49motr-rpc-cancel</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/27sns-repair-io-fail-test target=_blank>04motr-single-node/27sns-repair-io-fail-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/04motr-single-node/48motr-raid0-io target=_blank>04motr-single-node/48motr-raid0-io</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/40motr-dgmode target=_blank>05motr-single-node/40motr-dgmode</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/42motr-utils target=_blank>05motr-single-node/42motr-utils</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/13sns-repair-quiesce target=_blank>05motr-single-node/13sns-repair-quiesce</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/45motr-sns-repair-N-1 target=_blank>05motr-single-node/45motr-sns-repair-N-1</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/11sns-multi-tests target=_blank>05motr-single-node/11sns-multi-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/44motr-sns-repair target=_blank>05motr-single-node/44motr-sns-repair</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/14m0t1fs-fsync-test target=_blank>05motr-single-node/14m0t1fs-fsync-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/43motr-sync-replication target=_blank>05motr-single-node/43motr-sync-replication</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/38sns-abort-quiesce-test target=_blank>05motr-single-node/38sns-abort-quiesce-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/15m0t1fs-fwait-test target=_blank>05motr-single-node/15m0t1fs-fwait-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/18m0mount-test target=_blank>05motr-single-node/18m0mount-test</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/05motr-single-node/10sns-single-tests target=_blank>05motr-single-node/10sns-single-tests</a></br><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit/motr-single-node/62dix-repair-st-lookup-insert target=_blank>motr-single-node/62dix-repair-st-lookup-insert</a></p></details></td></tr><tr><td>Total</td><td>64</td><td><a href=http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/288//testReport/junit>:link:</a></td></tr></table><h2> CppCheck Summary</h2><p> &emsp;&emsp;&emsp;Cppcheck: No new warnings found :thumbsup:</p>

**Pull request merged**
