### PR TITLE
Updating the table with Title

### PR DESCRIPTION
**Pull request by VenkyOS**

### CODE REVIEW

**Review by huanghua78 — CHANGES_REQUESTED** [review]
1. A new column "Title" is added, but the column itself is not filled with titles. It is empty.
2. I changed the github rst file column to have relative path in https://github.com/Seagate/cortx-motr/pull/145
This was overwritten by this PR. Or, this PR was not created from 'main' branch. So, it did not contain the changes.
3. Some of the lines are broken.


Please view the files and ensure the page is in good shape.

**Comment by VenkyOS** [comment]
> 1. A new column "Title" is added, but the column itself is not filled with titles. It is empty.
> 2. I changed the github rst file column to have relative path in #145
>    This was overwritten by this PR. Or, this PR was not created from 'main' branch. So, it did not contain the changes.
> 3. Some of the lines are broken.
> 
> Please view the files and ensure the page is in good shape.

-  I will add the titles as part of the next PR.

-  Let me check about the relative path.

-  Some links are broken and this has been conveyed.

**Comment by huanghua78** [comment]
It looks better.
But this one is not fixed:
>I changed the github rst file column to have relative path in #145
>This was overwritten by this PR. Or, this PR was not created from 'main' branch. So, it did not contain the changes.

maybe you want to "update the branch"?

**Comment by huanghua78** [comment]
You have overwritten the changes in #145 .


commit cff481cdf2992bcd4d79a2d49c0e0c7dda921b92
Author: Huang Hua <hua.huang@seagate.com>
Date:   Fri Oct 23 05:24:46 2020 +0800

    Use relative path link in motr-design-doc-list (#145)

**Review by huanghua78 — COMMENTED** [review]
This patch overwritten the changes in #145 .

**Comment by VenkyOS** [comment]
Creating PRs based on tasks and closing this PR.

**Pull request closed without merging**
