### PR TITLE
CORTX-34091: Bytecount only tracks data bytes

### PR DESCRIPTION
**Pull request by AbhishekSahaSeagate**
Signed-off-by: Abhishek Saha <abhishek.saha@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by AbhishekSahaSeagate** [comment]
```[root@ssc-vm-g3-rhev4-0219 ~]# sleep 30 && kubectl exec -it cortx-data-g1-1 -c cortx-hax -- hctl status
Bytecount:
    critical : 0
    damaged : 157286400
    degraded : 0
    healthy : 0
Data pool:
    # fid name
    0x6f00000000000001:0x0 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x0 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
    cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local
    [started]  hax                 0x7200000000000001:0x0          inet:tcp:cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local@22001
    [started]  ioservice           0x7200000000000001:0x1          inet:tcp:cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local@21002
    [started]  confd               0x7200000000000001:0x2          inet:tcp:cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local@21001
    cortx-data-g0-1.cortx-data-headless.cortx.svc.cluster.local
    [started]  hax                 0x7200000000000001:0x3          inet:tcp:cortx-data-g0-1.cortx-data-headless.cortx.svc.cluster.local@22001
    [started]  ioservice           0x7200000000000001:0x4          inet:tcp:cortx-data-g0-1.cortx-data-headless.cortx.svc.cluster.local@21002
    [started]  confd               0x7200000000000001:0x5          inet:tcp:cortx-data-g0-1.cortx-data-headless.cortx.svc.cluster.local@21001
    cortx-data-g0-2.cortx-data-headless.cortx.svc.cluster.local
    [started]  hax                 0x7200000000000001:0x6          inet:tcp:cortx-data-g0-2.cortx-data-headless.cortx.svc.cluster.local@22001
    [started]  ioservice           0x7200000000000001:0x7          inet:tcp:cortx-data-g0-2.cortx-data-headless.cortx.svc.cluster.local@21002
    [started]  confd               0x7200000000000001:0x8          inet:tcp:cortx-data-g0-2.cortx-data-headless.cortx.svc.cluster.local@21001
    cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local
    [started]  hax                 0x7200000000000001:0x9          inet:tcp:cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local@22001
    [started]  ioservice           0x7200000000000001:0xa          inet:tcp:cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local@21002
    [started]  confd               0x7200000000000001:0xb          inet:tcp:cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local@21001
    cortx-data-g1-1.cortx-data-headless.cortx.svc.cluster.local  (RC)
    [started]  hax                 0x7200000000000001:0xc          inet:tcp:cortx-data-g1-1.cortx-data-headless.cortx.svc.cluster.local@22001
    [started]  ioservice           0x7200000000000001:0xd          inet:tcp:cortx-data-g1-1.cortx-data-headless.cortx.svc.cluster.local@21002
    [started]  confd               0x7200000000000001:0xe          inet:tcp:cortx-data-g1-1.cortx-data-headless.cortx.svc.cluster.local@21001
    cortx-data-g1-2.cortx-data-headless.cortx.svc.cluster.local
    [started]  hax                 0x7200000000000001:0xf          inet:tcp:cortx-data-g1-2.cortx-data-headless.cortx.svc.cluster.local@22001
    [started]  ioservice           0x7200000000000001:0x10         inet:tcp:cortx-data-g1-2.cortx-data-headless.cortx.svc.cluster.local@21002
    [started]  confd               0x7200000000000001:0x11         inet:tcp:cortx-data-g1-2.cortx-data-headless.cortx.svc.cluster.local@21001
    cortx-server-0.cortx-server-headless.cortx.svc.cluster.local
    [started]  hax                 0x7200000000000001:0x12         inet:tcp:cortx-server-0.cortx-server-headless.cortx.svc.cluster.local@22001
    [started]  rgw_s3              0x7200000000000001:0x13         inet:tcp:cortx-server-0.cortx-server-headless.cortx.svc.cluster.local@22501
    cortx-server-1.cortx-server-headless.cortx.svc.cluster.local
    [started]  hax                 0x7200000000000001:0x14         inet:tcp:cortx-server-1.cortx-server-headless.cortx.svc.cluster.local@22001
    [started]  rgw_s3              0x7200000000000001:0x15         inet:tcp:cortx-server-1.cortx-server-headless.cortx.svc.cluster.local@22501
    cortx-server-2.cortx-server-headless.cortx.svc.cluster.local
    [started]  hax                 0x7200000000000001:0x16         inet:tcp:cortx-server-2.cortx-server-headless.cortx.svc.cluster.local@22001
    [started]  rgw_s3              0x7200000000000001:0x17         inet:tcp:cortx-server-2.cortx-server-headless.cortx.svc.cluster.local@22501
```
Got this output after uploading a 150 mb file in 2+1 sns cluster

Observed a few problems:
Bytecount is shown as damaged, need to check if its a regression in main, or just with these custom changes.
Bytecount thread crashes, so after deleting the file, bytecount remained same and didn't return to 0.

**Comment by AbhishekSahaSeagate** [comment]
> Bytecount is shown as damaged, need to check if its a regression in main, or just with these custom changes.

Found the same behaviour in a separate custom build, unrelated to bytecount changes and based in main([custom build #7805](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/7805/)). This behaviour is seen when the cluster is restarted with ./shutdown-cortx-cloud.sh and ./start-cortx-cloud.sh
```
[root@ssc-vm-g4-rhev4-2211 k8_cortx_cloud]# kubectl exec -it cortx-data-g0-0 -c cortx-hax -- hctl status
Bytecount:
    critical : 0
    damaged : 79272345
    degraded : 0
    healthy : 0
Data pool:
    # fid name
    0x6f00000000000001:0x0 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x0 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
```
this was seen after writing 2 objects of 73 and 2 Mb respectively.

**Comment by AbhishekSahaSeagate** [comment]
Upon further investigation on m0trace file of hax, found that the controller conf objects are not in M0_NC_ONLINE pr M0_NC_REPAIRED state, thus are counted as failed. (Could be in DTM_RECOVERING state, but that info was not logged).
Due to these failures, the tolerance was exceeded and bytecount was shown as damaged.
```
1441110  37645110.011.289132  b7fc450  DEBUG   conf/pvers.c:840:conf_pver_nonhealty_recd_build     <6300000000000001:5> is failed
1441111  37645110.011.289426  b7fc4c0  CALL    conf/walk.c:97:conf_walker_down                     < rc=1
1441112  37645110.011.289746  b7fc4c0  CALL    conf/walk.c:124:conf_walker_up                      < rc=1
1441113  37645110.011.290290  b7fc460  CALL    conf/objs/objv.c:102:objv_lookup                    < rc=0
1441114  37645110.011.290380  b7fc4c0  CALL    conf/walk.c:124:conf_walker_up                      < rc=1
1441115  37645110.011.290670  b7fc4c0  CALL    conf/walk.c:124:conf_walker_up                      < rc=1
1441116  37645110.011.291286  b7fc460  CALL    conf/objs/objv.c:102:objv_lookup                    < rc=0
1441117  37645110.011.291376  b7fc4c0  CALL    conf/walk.c:124:conf_walker_up                      < rc=1
1441118  37645110.011.291664  b7fc4c0  CALL    conf/walk.c:124:conf_walker_up                      < rc=1
1441119  37645110.011.292306  b7fc460  CALL    conf/objs/objv.c:102:objv_lookup                    < rc=0
1441120  37645110.011.292394  b7fc4c0  CALL    conf/walk.c:124:conf_walker_up                      < rc=1
1441121  37645110.011.292690  b7fc4c0  CALL    conf/walk.c:124:conf_walker_up                      < rc=1
1441122  37645110.011.293548  b7fc460  CALL    conf/objs/pver.c:225:pver_lookup                    < rc=0
1441123  37645110.011.293638  b7fc4c0  CALL    conf/walk.c:124:conf_walker_up                      < rc=1
1441124  37645110.011.294118  b7fc4c0  CALL    conf/walk.c:116:conf_walker_up                      < rc=0
1441125  37645110.011.295084  b7fc580  DEBUG   conf/pvers.c:932:m0_conf_pver_status                state: 3, failures: 6
1441126  37645110.011.295354  b7fc580  DEBUG   conf/pvers.c:933:m0_conf_pver_status                failed objs of=<7600000000000001:0> srecd=[0 0 0 6 0]
1441127  37645110.011.295672  b7fc580  DEBUG   conf/pvers.c:934:m0_conf_pver_status                tolerance of=<7600000000000001:0> tolerance=[0 0 1 1 1]
1441128  37645110.011.295890  b7fc580  CALL    conf/pvers.c:936:m0_conf_pver_status                < rc=0
1441129  37645110.011.296228  b7fc680  CALL    spiel/cmd.c:2440:m0_spiel_conf_pver_status          < rc=0
1441131  37645179.340.880164  bffd900  DEBUG   ha/halon/interface.c:1227:m0_halon_interface_spiel   hi=0x55aafcee7a00 hii=0x55aafd525f80 spiel=0x55aafd533b60 working=1
```
there are 6 failures, all of them controllers, like <6300000000000001:5>
```
               if (!M0_IN(objv->cv_real->co_ha_state,
                          (M0_NC_ONLINE, M0_NC_REPAIRED))) {
                        M0_LOG(M0_DEBUG, FID_F" is failed",
```
This code checks for online and repaired state

**Comment by AbhishekSahaSeagate** [comment]
> Bytecount thread crashes, so after deleting the file, bytecount remained same and didn't return to 0.

after an investigation found that bytecount thread did not crash, but the rgw behaviour is changed. When an object is deleted, rgw updates the metadata, but does not actually delete the object for some time till garbage collector cleans-up. Due to this, actual space reclamation happens after some time and bytecount does not immediately gets reduced.
This is not an issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete

**Pull request closed without merging**
