### PR TITLE
EOS-24703-Enable_sns_systemTests_with_libfabric

### PR DESCRIPTION
**Pull request by swapnil-seagate**
Statement: SNS based ST's were disabled during the libfabric development. Now the libfabric code is in place and we need to re-enable the disabled ST's. While enabling the ST's we figured out that the current ST's are dependent on m0t1FS and m0tr kernel module.
Solution: With libfabric we dont need it anymore and hence converted the ST's to usermode ST's. As part of this ticket, I have added 3 new ST's which are alternate ST's to 15sns-repair-shutdown, 18sns-repair-quiesce and 18sns-repair-quiesce-failure.

Signed-off-by: Swapnil Chaudhary <swapnil.chaudhary@seagate.com>

# Problem Statement
- SNS based ST's were disabled during the libfabric development. Now the libfabric code is in place and we need to re-enable the disabled ST's. While enabling the ST's we figured out that the current ST's are dependent on m0t1FS and m0tr kernel module.
# Design
-  With libfabric we dont need it anymore and hence converted the ST's to usermode ST's. As part of this ticket, I have added 3 new ST's which are alternate ST's to 15sns-repair-shutdown, 18sns-repair-quiesce and 18sns-repair-quiesce-failure.

# Coding
   Checklist for Author
-  [Y ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [Y ] Unit and System Tests are added
- [Y ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ N] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ Y] JIRA number/GitHub Issue added to PR
- [ Y] PR is self reviewed
- [Y ] Jira and state/status is updated and JIRA is updated with PR link
- [ Y] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by madhavemuri** [comment]
@swapnil-seagate : Can you add them to <MOTR_SRC>/ .xperior/testds/motr-single_tests.yaml

**Comment by mehjoshi** [comment]
@swapnil-seagate , Please fix the Codacy reported issues.

**Comment by swapnil-seagate** [comment]
> @swapnil-seagate : Can you add them to <MOTR_SRC>/ .xperior/testds/motr-single_tests.yaml

Done.

**Review by nkommuri — APPROVED** [review]

**Review by mehjoshi — APPROVED** [review]
LGTM.

**Pull request merged**
