### PR TITLE
update contributors number related with cortx-motr

### PR DESCRIPTION
**Pull request by yanqingfu**
Signed-off-by: Yanqing Fu <yanqing.f.fu@seagate.com>

-----
[View rendered README.md](https://github.com/yanqingfu/cortx-motr/blob/patch-3/README.md)

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by mehjoshi** [comment]
@madhavemuri , @andriytk , Can you review the following change?

**Review by mehjoshi — APPROVED** [review]
LGTM

**Review by nkommuri — APPROVED** [review]

**Comment by mehjoshi** [comment]
ok to test

**Pull request merged**
