### PR TITLE
EOS-15263 beck: correct the sequence of m0_mutex_fini and m0_thread_fini

### PR DESCRIPTION
**Pull request by RakeshVaghasiya**
Issue: Mutex fini called before thread fini. If thread has not completed
work yet then got the panic mutex is in use.

Fix: m0_mutex_fini called after the m0_thread_fini

### CODE REVIEW

**Review by mukundkanekar — APPROVED** [review]

**Review by NikhilBirgade — APPROVED** [review]

**Review by shashank-parulekar — APPROVED** [review]

**Review by huanghua78 — APPROVED** [review]

**Comment by huanghua78** [comment]
@RakeshVaghasiya please resolve the conflict.
#82 and #197 are merged, and there are some conflicts.

**Comment by huanghua78** [comment]
Do we need this to be merged to cortx-1.0?

**Comment by RakeshVaghasiya** [comment]
> @RakeshVaghasiya please resolve the conflict.
> #82 and #197 are merged, and there are some conflicts.

Merged with main

**Comment by RakeshVaghasiya** [comment]
> Do we need this to be merged to cortx-1.0?

Yes, We need this

**Pull request merged**
