### PR TITLE
CORTX-30957: Fixed critical issues for the Codacy patterns.

### PR DESCRIPTION
**Pull request by RohanDhodare**
Fixed the codacy warning.
warning: "subprocess call with shell=True identified, security issue."

Signed-off-by: Rohan Dhodare <rohan.v.dhodare@seagate.com>

# Problem Statement
- Getting Critical Codacy pattern warning as "subprocess call with shell=True identified, security issue."

# Design
-  I have set shell=False which has solved the ciritical error, however after doing that I'm observing another warning which needs to be ignored.

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by RohanDhodare** [comment]
As mentioned in the description of PR the new warning which is observed is "subprocess call - check for execution of untrusted input."  According to the [PyCQA/bandit#333](https://github.com/PyCQA/bandit/issues/333 ) the warning observed can be ignored.

**Comment by rkothiya** [comment]
Can one of the admins verify this patch?

**Comment by rkothiya** [comment]
retest this please

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete

**Pull request closed without merging**
