### PR TITLE
Markdown file upload

### PR DESCRIPTION
**Pull request by swatid-seagate**
# Problem Statement
- .rst files are converted to markdown and uploaded

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

-----
[View rendered doc/HLD-FOP-State-Machine.md](https://github.com/swatid-seagate/cortx-motr/blob/md-file-upload/doc/HLD-FOP-State-Machine.md)

### CODE REVIEW

**Review by mehjoshi — APPROVED** [review]
This pull request merely converts the source files from .rst to .md format.
The contents of the various files themselves are not under review here.
So, I approve the changes.

**Review by nkommuri — APPROVED** [review]

**Comment by novium258** [comment]
Please merge this, thank you.

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by rkothiya** [comment]
Since this is a documentation change giving an exception for ci/cd and 1n/3n deployment jobs

**Pull request merged**
