### PR TITLE
Sage arm port

### PR DESCRIPTION
**Pull request by Nalini-Seagate**
This is new PR for merging Sage2.0 code base on to the sage arm code base. This holds all the changes in master branch since it was last forked in sage-base-1.0 as well as the some code changes with respect to the ARM platform. After the merge of this PULL request, it need to be rebased on to the final master branch later
-----
[View rendered CONTRIBUTING.md](https://github.com/Nalini-Seagate/cortx-motr/blob/sage_arm_port/CONTRIBUTING.md)
[View rendered SUPPORT.md](https://github.com/Nalini-Seagate/cortx-motr/blob/sage_arm_port/SUPPORT.md)

### CODE REVIEW

**Comment by huanghua78** [comment]
Please elaborate what this PR does.

**Comment by Nalini-Seagate** [comment]
@huanghua78 , This is new PR for rebasing Sage2.0 code base on to the sage arm code base. This holds all the changes in master branch since it was last forked in sage-base-1.0 as well as the some code changes with respect to the ARM platform. After the merge of this PULL request, it need to be rebased on to the final master branch.

**Comment by huanghua78** [comment]
> @huanghua78 , This is new PR for rebasing Sage2.0 code base on to the sage arm code base. This holds all the changes in master branch since it was last forked in sage-base-1.0 as well as the some code changes with respect to the ARM platform. After the merge of this PULL request, it need to be rebased on to the final master branch.

This must be included in the description of this PR. It should not be "null".
Otherwise, reviewers and gatekeepers don't know the purpose of this PR.

It's better not to mix a fix and a rebase.
So, the reviewers and gatekeepers can know where to look at.

**Comment by Nalini-Seagate** [comment]
@huanghua78 , it is not rebase  as of now, As it is required to merge the Sage 2.0  master branch change unto the sage arm port for   merging  and some local fix  only , and later it need to be rebased  against the main master branch

**Comment by andriytk** [comment]
Please, rebase your code against sage-base-2.0 tag so that the patch and diff would include only your changes.

**Comment by huanghua78** [comment]
> Please, rebase your code against sage-base-2.0 tag so that the patch and diff would include only the changes related to ARM porting.

@Nalini-Seagate please do as @andriytk suggested.
Otherwise, this PR is totally not reviewable.

**Comment by huanghua78** [comment]
> > Please, rebase your code against sage-base-2.0 tag so that the patch and diff would include only the changes related to ARM porting.
> 
> @Nalini-Seagate please do as @andriytk suggested.
> Otherwise, this PR is totally not reviewable.

1. Create a branch in Seagate/cortx-motr repo, based on sage-base-2.0 tag. (the "sage_arm_port" should be the one, in this case. Or you can new another name)
2. rebase all your current changes on this branch.
3. Create a PR against this branch.

**Comment by andriytk** [comment]
It was replaced with https://github.com/Seagate/cortx-motr/pull/971, so I'm closing it.

**Pull request closed without merging**
