### PR TITLE
Update idx.h. Remove duplicate doc

### PR DESCRIPTION
**Pull request by mengwanguc**
Remove duplicate documentation because they are a copy-paste of comments from https://github.com/Seagate/cortx-motr/blob/main/motr/client.h#L368.

Instead, add a reference to motr/client.h.

Users can also find more detailed descriptions of the index K-V store in client.h

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by andriytk — APPROVED** [review]

**Comment by mengwanguc** [comment]
Hi @andriytk , thanks for your review! Do you think this PR is good enough to merge, or do we need review from someone else?

Thanks!

**Comment by andriytk** [comment]
At least one more approval is needed. Let's ask @huanghua78.

**Review by huanghua78 — APPROVED** [review]
Looks fine.

**Comment by mengwanguc** [comment]
Hi @andriytk , can you help merge this PR? It already receives 2 approvals.

(BTW I'm a Seagate employee so I don't need to sign the CLA.)

Thank you very much!

**Comment by andriytk** [comment]
@mengwanguc, I'm afraid you do need to sign the CLA if you created the patch from a GitHub account which is not part of Seagate org.

**Comment by johnbent** [comment]
Thanks @andriytk .  The CLA is not necessary here.  Even if Meng wasn't employed by Seagate right now, then this would still be allowed as a community contribution without requiring CLA.  Please refer to [https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md](https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md) for more info.  And thanks for being so careful and awesome with the community!

**Review by johnbent — APPROVED** [review]

**Comment by mengwanguc** [comment]
Hi @madhavemuri , @huanghua78 and @mehjoshi , can some of you help me merge this PR? It already gets 3 approvals. Thank you very much!

**Comment by mehjoshi** [comment]
Hi @mengwanguc, I will take care of merging it.

**Review by mehjoshi — APPROVED** [review]

**Comment by mehjoshi** [comment]
I will go ahead and merge it without waiting for VM Deployment test as it doesn't seem necessary here.

**Pull request merged**
