### PR TITLE
Update Quick-Start-Guide.rst

### PR DESCRIPTION
**Pull request by mengwanguc**
Need to be root user when modifying `/etc/modprobe.d/lnet.conf` and running `python -m pip uninstall pip setuptools`.
Otherwise permission errors will happen

Signed-off-by: Meng Wang <mengwanguc@gmail.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by huanghua78 — APPROVED** [review]

**Comment by mengwanguc** [comment]
Hi @huanghua78 , thanks for approving my PR! Do you think this PR is good enough to merge, or do we need another approval from someone else?

**Comment by huanghua78** [comment]
> Hi @huanghua78 , thanks for approving my PR! Do you think this PR is good enough to merge, or do we need another approval from someone else?

Please try to fix the "verification/cla-signed" issue.
Also, please note, the DCO (signoff-by) is duplicated in original commit. Please also fix it.

You may need to check if your local git config is correct.
You account on github.com is set properly. (email address is the same as your local username).

**Comment by mengwanguc** [comment]
> > Hi @huanghua78 , thanks for approving my PR! Do you think this PR is good enough to merge, or do we need another approval from someone else?
> 
> Please try to fix the "verification/cla-signed" issue.
> Also, please note, the DCO (signoff-by) is duplicated in original commit. Please also fix it.
> 
> You may need to check if your local git config is correct.
> You account on github.com is set properly. (email address is the same as your local username).

Thanks Hua, I've fixed the DCO issue and my "git config" as well.

I'm currently a Seagate employee (intern) so I think I don't need to sign CLA.

(e.g. John merged my PR here https://github.com/Seagate/cortx/pull/1089 without my CLA signature)

**Review by mehjoshi — APPROVED** [review]

**Pull request merged**
