### PR TITLE
EOS-10682 xperior/testds: test group created for motr single node test

### PR DESCRIPTION
**Pull request by bansisoni**
- total 5 group created 01motr-single-node to 05motr-single-node
- If no test group assigned, motr-single-node as a default

Signed-off-by: Bansidhar Soni <bansidhar.soni@seagate.com>

### CODE REVIEW

**Comment by huanghua78** [comment]
Please explain:
1. why five groups {01motr-single-node ~ 05motr-single-node} are created?
2. How to classify the test cases into different groups? What are the standards? How do we put them into different groups?

**Review by nihar1313 — APPROVED** [review]

**Comment by bansisoni** [comment]
> Please explain:
> 
> 1. why five groups {01motr-single-node ~ 05motr-single-node} are created?
> 2. How to classify the test cases into different groups? What are the standards? How do we put them into different groups?

1. Me and Madhav decided to run motr test on 5 parallel vm, so created 5 group.
2. Madhav divided tests into group. Not much idea about this. @madhavemuri any input on this.
Purpose of this changes to run parallel on multiple vm so PR test time can be reduce to 1-2 hr.

**Comment by bansisoni** [comment]
https://github.com/Seagate/seagate-ci/pull/11

**Review by huanghua78 — APPROVED** [review]

**Comment by bansisoni** [comment]
Do not merge this pull request, before https://github.com/Seagate/seagate-ci/pull/11

**Comment by madhavemuri** [comment]
@bansisoni : Can we apply these groups for HW jenkins nodes too ?

**Comment by bansisoni** [comment]
> @bansisoni : Can we apply these groups for HW jenkins nodes too ?

Yes

**Pull request merged**
