### PR TITLE
CORTX-32081: Codacy code cleanup (#1858)

### PR DESCRIPTION
**Pull request by rkothiya**
This patch fixes some of the codacy warnings.
warning fixed : "pep257 tool"

Signed-off-by: Rinku Kothiya <rinku.kothiya@seagate.com>

# Problem Statement
warning fixed : "pep257 tool"

# Design
Inserted a blank line before function defination

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by rkothiya** [comment]
Since we have only added blank lines to fix this, I do not think running the test and wasting resource is worth it, hence not running the test.

**Comment by rkothiya** [comment]
As per the discussion in the Codacy meeting, fixing this can cause a new warning due to problem in codacy tool. Hence we want to put this on hold until that is solved.

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by huanghua78 — APPROVED** [review]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete

**Pull request closed without merging**
