### PR TITLE
EOS-27717: take a lock before using this AST

### PR DESCRIPTION
**Pull request by huanghua78**
This will reduce the race condition, but there
is still possibility the AST is reused before it is completely processed.

Signed-off-by: Hua Huang <hua.huang@seagate.com>

# Problem Statement
AST is reused before it is completely processed.

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by siningwuseagate** [comment]
@huanghua78 To help me understand the context of this issue, could you elaborate the race condition in a bit more details? and also what test you use to observe it, what behavior we will see from the test? As I observe a hang (for a period of time, not forever) during my FDMI test in my rgw implementation, I would like to know if the issue I observe is the same as the one here.
To completely eliminate the race, what is the proper solution?

**Comment by huanghua78** [comment]
> @huanghua78, who do you mean by "we" that don't know when ast is finished processing? User callback (`->sa_cb()`) is called from `m0_sm_asts_run()`, so the user code in the callback knows when it's finished, and it can re-use the ast accordingly (if needed).
> 
> Please, help me to understand the issue. Maybe I could help then.

The user or the owner of this `ast`.


```
492 /**
493    Asynchronous system trap.
494
495    A request to execute a call-back under group mutex. An ast can be posted by a
496    call to m0_sm_ast_post() in any context.
497
498    It will be executed later, see AST section of the comment at the top of this
499    file.
500
501    Only m0_sm_ast::sa_cb and m0_sm_ast::sa_datum fields are public. The rest of
502    this structure is for internal use by sm code.
503  */
504 struct m0_sm_ast {
505         /** Call-back to be executed. */
506         void              (*sa_cb)(struct m0_sm_group *grp, struct m0_sm_ast *);
507         /** This field is reserved for the user and not used by the sm code. */
508         void               *sa_datum;
509         struct m0_sm_ast   *sa_next;
510         struct m0_sm       *sa_mach;
511 };

...

 328 static void wakeup_iff_waiting(struct m0_sm_group *grp, struct m0_sm_ast *ast)
 329 {
 330         struct m0_fom *fom = ast->sa_datum;
 331
 332         M0_ENTRY();
 333         if (m0_fom_is_waiting(fom))
 334                 m0_fom_ready(fom);
 335         M0_LEAVE();
 336 }
 337
 338 M0_INTERNAL void m0_fdmi__src_dock_fom_wakeup(struct fdmi_sd_fom *sd_fom)
 339 {
 340         struct m0_fom *fom;
 341
 342         M0_ENTRY("sd_fom %p", sd_fom);
 343         M0_PRE(sd_fom != NULL);
 344
 345         fom = &sd_fom->fsf_fom;
 346
 347         /**
 348          * FOM can be uninitialized here, because posting
 349          * is allowed even if FDMI service is not started
 350          * @todo Small possibility of races exist (Phase 2).
 351          */
 352         if (fom == NULL || fom->fo_loc == NULL) {
 353                 M0_LEAVE("FDMI FOM is not initialized yet");
 354                 return;
 355         }
 356         if (sd_fom->fsf_wakeup_ast.sa_next == NULL) {
 357                 sd_fom->fsf_wakeup_ast = (struct m0_sm_ast) {
 358                         .sa_cb    = wakeup_iff_waiting,
 359                         .sa_datum = fom
 360                 };
 361                 m0_sm_ast_post(&fom->fo_loc->fl_group, &sd_fom->fsf_wakeup_ast);
 362         }
 363         M0_LEAVE();
 364 }

```

m0_fdmi__src_dock_fom_wakeup() will be called repeatedly to wakeup the FDMI source dock fom.
`sd_fom->fsf_wakeup_ast` is passed to m0_sm_ast_post();
The AST will be executed later, asynchronously.

The user or owner of the AST, does not know if it is safe to re-use the `sd_fom->fsf_wakeup_ast`.
This is a generic problem in the m0_sm_ast_post()/m0_sm_asts_run(), I think.

Maybe this is a special way to use the AST in FDMI, and it is not the correct way.
As I explained in the https://jts.seagate.com/browse/EOS-27717, the possible fix is to dynamically allocate a new AST, and setup the AST's data/callback, and post it.
@madhavemuri , @andriytk , how do you think?

But this problem may still exist for other places.

**Comment by andriytk** [comment]
I think the race problem is in this check: `if (sd_fom->fsf_wakeup_ast.sa_next == NULL)`. As far as I understand, you are trying to verify here whether the ast is already posted and pending, and if it is - don't post it again. Which is a fair check, but done in a wrong way, I'm afraid.

First, according to the documentation, `sa_next` is an internal field, and it is not supposed to be used by users:

```
   Only m0_sm_ast::sa_cb and m0_sm_ast::sa_datum fields are public. The rest of
   this structure is for internal use by sm code.
 */
struct m0_sm_ast {
```

Second, users must make sure to not call `m0_sm_ast_post()` of the same ast until its execution from the previous post is complete:

```
 * An AST must not be re-posted until its previous (already posted) execution
 * completes.
 */
M0_INTERNAL void m0_sm_ast_post(struct m0_sm_group *grp, struct m0_sm_ast *ast);
```

So looks like, as of today, m0_sm does not provide any API to check or make sure that an ast is already posted or in the middle of execution, and users must do this check on their own somehow.

**Comment by andriytk** [comment]
@huanghua78, could this be a possible solution to your problem - https://github.com/Seagate/cortx-motr/pull/1471 ?

**Comment by huanghua78** [comment]
> @huanghua78, could this be a possible solution to your problem - #1471 ?

Let's have thorough test to verify it.
I am not sure if this would help.

**Comment by huanghua78** [comment]
> I think the race problem is in this check: `if (sd_fom->fsf_wakeup_ast.sa_next == NULL)`. As far as I understand, you are trying to verify here whether the ast is already posted and pending, and if it is - don't post it again. Which is a fair check, but done in a wrong way, I'm afraid.
> 
> First, according to the documentation, `sa_next` is an internal field, and it is not supposed to be used by users:
> 
> ```
>    Only m0_sm_ast::sa_cb and m0_sm_ast::sa_datum fields are public. The rest of
>    this structure is for internal use by sm code.
>  */
> struct m0_sm_ast {
> ```
> 
> Second, users must not post the same ast again until its execution from the previous post is complete:
> 
> ```
>  * An AST must not be re-posted until its previous (already posted) execution
>  * completes.
>  */
> M0_INTERNAL void m0_sm_ast_post(struct m0_sm_group *grp, struct m0_sm_ast *ast);
> ```
> 
> So looks like, as of today, m0_sm does not provide any API to check or make sure that an ast is already posted or in the middle of execution, and users must do this check on their own. Probably, via `sa_datum` somehow. (`sa_datum` is usually a pointer to some user data structure which can have a flag for this purpose.) And I do agree - it is inconvenient.


The code was from original FDMI implementation. It was not tested by heavy run. So, this problem was not revealed at that time.
But the issue here is generic for all use cases of m0_sm_ast_post() throughout the Motr code.

When the owner of `ast` calls m0_sm_ast_post(grp, ast), the owner does not know when it is safe to re-use the `ast`.
If `ast` is not re-used at all, it is fine.
If `ast` is re-used, there might be some race conditions.

**Comment by andriytk** [comment]
> When the owner of `ast` calls m0_sm_ast_post(grp, ast), the owner does not know when it is safe to re-use the `ast`. If `ast` is not re-used at all, it is fine. If `ast` is re-used, there might be some race conditions.

Agree. That's why we have this ugly code with additional flags and locks to workaround this issue, for example here: https://github.com/Seagate/cortx-motr/blob/7c149e0f05e3f79d3c2b97469d86f511db59b288/ha/link.c#L1649-L1660

**Comment by andriytk** [comment]
> When the owner of `ast` calls m0_sm_ast_post(grp, ast), the owner does not know when it is safe to re-use the `ast`. If `ast` is not re-used at all, it is fine. If `ast` is re-used, there might be some race conditions.

@huanghua78, see the latest code at https://github.com/Seagate/cortx-motr/pull/1471 where `m0_sm_ast_post()` can be called anytime and even concurrently by several threads.

**Comment by huanghua78** [comment]
Let me close it and use #1471

**Pull request closed without merging**
